### ISSUE TITLE
[BUG] City is not printed on shipping label

### ISSUE THREAD

**Issue by hans2103** [tig-nl/postnl-magento2#262] opened 2021-07-07 13:23 UTC
**To Reproduce**
1. Go to `Magento Beheer > Winkels > Instellingen > Configuratie > Verkopen > PostNL > Basic > Algemene Configuratie en accountinformatie > Adres van Afzender`
2. Add the address including city
3. Go to `Magento > Sales and print a shipping label`

**Expected result**
The entire address including city is printed in the top left corner of the shipping label.

**Actual result**
The city is not printed on the shipping label

**Workaround**
None

**Screenshots**

**Please complete the following information**
- Magento version: Magento 2.4.2
- PHP version: 7.3.28
- TIG PostNL version: 1.9.8

**Comment by tig-jeffreybranderhorst** [comment] 2021-07-08 07:14
Hi @hans2103 ,

I tested this and was not able to reproduce this. Could you contact digitaleklantsupport@postnl.nl for further support. We will then investigate it further in your environment to see what is going wrong. 

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment] 2021-08-12 09:36
Hi @hans2103 ,

I will close this issue, if you are still having problems we recommend you contact digitaleklantsupport@postnl.nl for further support.

Have a great day,
Jeffrey

**Closed by tig-jeffreybranderhorst** 2021-08-12 09:36 UTC

**Comment by hans2103** [comment] 2021-09-08 12:56
@tig-jeffreybranderhorst contacted them directly after your message. Issue has not been solved yet.
