### ISSUE TITLE
[BUG] Incorrect table rate using weight

### ISSUE THREAD

**Issue by abvdveen** [tig-nl/postnl-magento2#319] opened 2022-07-05 10:05 UTC
Using [these table rates](https://www.pegasusboek.nl/matrixrates.csv), a client got the wrong shipping price.

The order was from NL, and according to the debug log had a weight of 10000 (<ns1:Weight>10000</ns1:Weight>). So the first rule should apply, leading to shipping costs of 6.50.

Instead the shipping costs where 34.30, which implies rule 28 was applied. Which doesn't match the weight (applies to 2 - 5 kg) and should never be triggered, as NL rule apply.

Is this related to #293 ?

- Magento 2.3.7-p3
- PHP 7.4
- TIG PostNL 1.12.2

**Comment by tig-jeffreybranderhorst** [comment] 2022-07-05 12:41
Hi @abvdveen ,

We cannot download the CSV to test it, we also couldt reproduce this with our own CSV's. The best way to let us investigate this further is to contact PostNL at digitaleklantsupport@postnl.nl. Then PostNL will investigate your CSV and if needed they will forward the issue to us.

Have a great day,
Jeffrey

**Comment by abvdveen** [comment] 2022-07-05 12:59
Sorry, link [should be this](https://www.pegasusboek.nl/matrixrate.csv). Could you give it another try, or should I contact  [digitaleklantsupport@postnl.nl](mailto:digitaleklantsupport@postnl.nl)?

**Comment by tig-jeffreybranderhorst** [comment] 2022-07-06 07:55
Hi @abvdveen,

I can indeed download it now, I would like to ask you to indeed contact digitaleklantsupport@postnl.nl because then we can give support while looking at your environment to see what settings are active and why this is happening. 

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment] 2022-07-15 13:11
Hi @abvdveen ,

If PostNL is not able to help you further with this issue, they will make an issue in our support, and we will then contact you. Because PostNL should provide you the support at this moment, we will close this issue.  If you have not yet contacted PostNL we suggest you contact them at digitaleklantsupport@postnl.nl
 
Have a great day,
Jeffrey

**Closed as completed by tig-jeffreybranderhorst** 2022-07-15 13:11 UTC

**Comment by abvdveen** [comment] 2022-08-05 13:09
@tig-jeffreybranderhorst : it turned out to be a bug, similar to #293. After debugging Service/Carrier/Price/Matrixrate.php I discovered rules are still not sorted correctly. If you have general rules in the matrix csv, where country = *, such a rule may be selected instead of a 100% matching rule on country.

A matching rule on country should always have preference above a general one.

Adding a sort on destiny_country_id in `$matrixrateCollection     = $this->matrixrateCollection->addOrder('destiny_country_id', 'DESC')->addOrder('subtotal', 'DESC')->addOrder('weight', 'DESC');` in Service/Carrier/Price/Matrixrate.php fixes the issue.

**Comment by tig-jeffreybranderhorst** [comment] 2022-08-08 07:17
Hi @abvdveen ,

Thank you for contacting us, and giving an update about this issue. I want to ask you to send this to PostNL themselves so they can test this, you can contact them via digitaleklantsupport@postnl.nl 

Have a great day,
Jeffrey

**Comment by abvdveen** [comment] 2022-08-08 08:37
Hi @tig-jeffreybranderhorst ,

I already had an extended conversation with them via that email address. It turned out they don't know themselves how their plugin is built. I almost started to break up the rules in my matrix csv, because 'you cannot have more then one country on a single line'. 

But knowing this setup has been working for years, I decided to have a look in the code myself and saw it's perfectly ok to have rows with multiple countries - see function validate in Service/Validation/Country.php

So now I had to find the real cause and after debugging the order proces, that turned out to be the sorting of the rules.

Tomorrow a technical person at PostNL will look into the matter, John van Persie of PostNL mailed me...

Best,
Albert

**Comment by tig-jeffreybranderhorst** [comment] 2022-08-08 08:59
Hi @abvdveen ,

Good te read you already have contacted PostNL and that a technical is going to investigate it. Just so you know, I added this to our backlog myself, but still PostNL is in the lead, and they decide what we fix first. 

Thank you again for submitting and thinking along! 

Have a great day,
Jeffrey

**Comment by abvdveen** [comment] 2022-08-08 09:06
Thanks, made a note for myself to check future upgrades of the module on whether this fix has already been incorporated. Otherwise have to add it again to the updated version...

**Comment by tig-jeffreybranderhorst** [comment] 2022-08-08 13:59
Hi @abvdveen,

Smart! We will add it as soon as possible! 

Have a great day,
Jeffrey

**Comment by abvdveen** [comment] 2023-07-05 09:56
@tig-jeffreybranderhorst: It turns out this isn't correctly fixed in your code. Upgraded to Magento 2.4.5 and 1.12.8 of your module and matrix rates were wrong again. Looking at the code in Service/Carrier/Price/Matrixrate.php I noticed the order of the addOrder clauses in function getRate is wrong. You have:
`$matrixrateCollection     = $this->matrixrateCollection->addOrder('subtotal', 'DESC')->addOrder('weight', 'DESC')->addOrder('destiny_country_id', 'DESC');`

Should be:
`$matrixrateCollection     = $this->matrixrateCollection->addOrder('destiny_country_id', 'DESC')->addOrder('subtotal', 'DESC')->addOrder('weight', 'DESC');`
