### ISSUE TITLE
[BUG] Module is not compatible with Magento 2.3.4.

### ISSUE THREAD

**Issue by SimonPrins** [tig-nl/postnl-magento2#154] opened 2020-01-24 14:35 UTC
**To Reproduce**
1. Try installing Magento 2.3.4 through composer
2. Installation will fail, since tig/postnl-magento2 only allows magento version up to 2.3.3. (magento/framework version 102.0.4, corresponding to magento 2.3.4 is not allowed according to the composer.json)

**Expected result**
Magento upgrades correctly.

**Actual result**
Upgrade command fails since requirements can't be met.

**Workaround**
None

** Please complete the following information**
- Magento version: 2.3.4
- PHP version: 7.2.0
- TIG PostNL version: 1.8.1

**Comment by tig-svenluiks** [comment] 2020-01-24 14:45
Hi @SimonPrins ,

We are currently testing this ourselves as well. Because we have had negative experiences creating RC's with customers installing them on their production environment without testing, we have decided not to create RC's anymore, at least for now.

If you would like to test the extension on 2.3.4 on your own environment, I recommend creating a fork off our repository to change the composer version.

**Comment by tig-dennisvanderhammen** [comment] 2020-01-24 16:03
As this is a duplicate of #150 I will be closing this issue.

**Closed** 2020-01-24 16:03 UTC
