### ISSUE TITLE
Facing issue after update the magento to magento 2.3.4 

### ISSUE THREAD

**Issue by Tanuja0202** [tig-nl/postnl-magento2#159] opened 2020-03-02 05:18 UTC

**Comment by tig-jaspersmits** [comment] 2020-03-02 07:44
@Tanuja0202 ,

Thanks for contacting us. Unfortunate to hear you are experiencing this problem. With what action do you get to see this error? Did you also test this on a clean Magento environment with no themes and no other extensions enabled?

Looking forward to your response.

Kind regards,
Jasper
TIG

**Comment by Tanuja0202** [comment] 2020-03-02 12:35
@tig-jaspersmits 
It is working fine on the 2.3.3 version. After the update, it is showing this issue.
Go to order section in the admin > action(postnl-create shipment,print label)without selecting any order

**Comment by tig-jaspersmits** [comment] 2020-03-02 13:18
Hi @Tanuja0202 ,

I understand. I was able to reproduce it, but doesn't seem to be that big of a problem since you should select orders in the order grid. But I agree that throwing an exception like this isn't great. I have put this on the backlog.

Thanks for letting us know. I do have a small favour to ask, could you use the template on Github next time when creating an issue like this? Thanks in advance!

Kind regards,
Jasper
TIG

**Comment by Tanuja0202** [comment] 2020-03-02 13:30
So there is any solution for this issue?

**Comment by tig-jaspersmits** [comment] 2020-03-03 07:31
@Tanuja0202 ,
It will be fixed in an upcoming release of the extension. Currently I don't have an ETA for that yet. You can keep an eye on the release notes here: https://docs.tig.nl/x/3YSC

Kind regards,
Jasper

**Comment by Tanuja0202** [comment] 2020-03-03 10:45
*Fatal error*: Uncaught TypeError: Argument 2 passed to
TIG\PostNL\Service\Handler\BarcodeHandler::canAddReturnBarcodes() must
implement interface TIG\PostNL\Api\Data\ShipmentInterface, null given,
called in /var/www/vhosts/
stagefreaks.webshopmagento.nl/vendor/tig/postnl-magento2/Service/Handler/BarcodeHandler.php
on line 322 and defined in /var/www/vhosts/
stagefreaks.webshopmagento.nl/vendor/tig/postnl-magento2/Service/Handler/BarcodeHandler.php:294
Stack trace: #0 /var/www/vhosts/
stagefreaks.webshopmagento.nl/vendor/tig/postnl-magento2/Service/Handler/BarcodeHandler.php(322):
TIG\PostNL\Service\Handler\BarcodeHandler->canAddReturnBarcodes('BE', NULL)
#1 /var/www/vhosts/
stagefreaks.webshopmagento.nl/vendor/tig/postnl-magento2/Service/Handler/BarcodeHandler.php(138):
TIG\PostNL\Service\Handler\BarcodeHandler->validateShipment('139683', 'BE')
#2 /var/www/vhosts/
stagefreaks.webshopmagento.nl/vendor/tig/postnl-magento2/Controller/Adminhtml/Shipment/MassPrintPackingslip.php(125):
TIG\PostNL\Service\Handler\BarcodeHandler->prepa in
*/var/www/vhosts/stagefreaks.webshopmagento.nl/vendor/tig/postnl-magento2/Service/Handler/BarcodeHandler.php
<http://stagefreaks.webshopmagento.nl/vendor/tig/postnl-magento2/Service/Handler/BarcodeHandler.php>*
on
line
*294*

After selecting the orders we are getting this error.

**Comment by tig-jaspersmits** [comment] 2020-03-03 11:01
Please create a new Github issue using the template. Thank you.

**Closed** 2020-04-20 10:38 UTC
Labels: on backlog
