### ISSUE TITLE
[BUG] Special characters show as encoded strings on labels and package slips 

### ISSUE THREAD

**Issue by thioz** [tig-nl/postnl-magento2#242] opened 2021-03-22 08:15 UTC
**To Reproduce**
1. Go to shipping of an order with an address containing a special character like an apostrophe
2. Click on 'Print Label'
3. Look at address line

**Expected result**
See the address as it was entered 

**Actual result**
Special characters are shown in hex/htmlentity format

**Workaround**
None

** Please complete the following information**
- Magento version: Magento  2.3.5-p2
- PHP version: 7.3
- TIG PostNL version: 1.9

**Comment by tig-jeffreybranderhorst** [comment] 2021-03-22 10:54
Hey @thioz ,

Thank you for submitting this! I will test it and if it is reproducible we will put this on our backlog.
Could you share the address you are having issues with?

Have a great day,
Jeffrey

**Comment by thioz** [comment] 2021-03-22 11:47
Hi Jeffrey,

The streetname was : 't Haantje

Cheers

Op ma 22 mrt. 2021 om 18:54 schreef Jeffrey Branderhorst <
***@***.***>:

**Comment by tig-jeffreybranderhorst** [comment] 2021-03-22 12:01
Hi @thioz ,

We are not able to reproduce the issue with a street with ' 
Is it possible you contact us at support@tig.nl so we can help you further and investigate this on your webshop. 

Have a great day,
Jeffrey

**Comment by thioz** [comment] 2021-03-22 12:15
Hi Jeffrey,

I have attached a screenshot of the address and the package slip PDF so you
can see what happens.

Kind regards

Rob




Op ma 22 mrt. 2021 om 20:01 schreef Jeffrey Branderhorst <
***@***.***>:

**Comment by tig-jeffreybranderhorst** [comment] 2021-03-22 14:03
Hi @thioz ,

Looks like there are no attachment I guessing github removes those. Could you send them to support@tig.nl ?

Have a great day,
Jeffrey

**Comment by thioz** [comment] 2021-04-19 12:07
Hi Jeffrey, 

I sent this to support but have yet to hear back from you. 

Kind regards 
Rob

**Comment by tig-jeffreybranderhorst** [comment] 2021-04-19 13:23
Hi @thioz ,

That is strange, do you have an issue number of our support system so I can check what the status of the issue is.

Have a great day,
Jeffrey

**Comment by tig-vincentthart** [comment] 2021-06-09 09:46
Hi @thioz,

Because we could not reproduce this issue we will close it. If you have any questions, feel free to contact our support team.

Kind regards,
Vincent

**Closed by tig-vincentthart** 2021-06-09 09:46 UTC
