### ISSUE TITLE
PostNL toolbar messing up grid(s) other than order and shipment grid

### ISSUE THREAD

**Issue by kaybeudeker** [tig-nl/postnl-magento2#67] opened 2018-09-05 13:58 UTC
### Preconditions
- magento/product-community-edition 2.2.5
- tig/postnl-magento2 1.5.0

### Steps to reproduce
- Backend: open **Reports > Marketing Automation > Crons Tasks**
This issue occurs on custom modules with a custom grid as well

### Expected result
- A grid where dropdowns are working as expected (with selectable options)

### Actual result
PostNL toolbar messing up the dropdown(s) above the columns (no options to select):

![postnl-toolbar-error-m2](https://user-images.githubusercontent.com/31165120/45097870-1a1f5480-b124-11e8-9e62-d886c9c1a6d3.png)

**Comment by tig-jaspersmits** [comment] 2018-09-06 07:40
Good morning Kay,

Thank you for submitting this and unfortunate to hear that this isn't working as intended. I just created a backlog issue for this and our team will look into it. This will be solved in a future update. What i can do is subscribe you to our release notes page, this way you will get an update once a new version is released and you can check the notes to see if they fixed it in the release.

If you can provide me your mailaddress i can add you, or you can subscribe on the release notes page yourself over here: https://confluence.tig.nl/x/3YSC

Kind regards,

Jasper 
TIG

**Comment by tig-rikjonkmans** [comment] 2018-11-29 13:20
Fixed in the new release 1.6.0

**Closed by tig-rikjonkmans** 2018-11-29 13:20 UTC
