### ISSUE TITLE
[BUG] Selected pickup location is gone after refreshing or revisiting the checkout

### ISSUE THREAD

**Issue by simonjanguapa** [tig-nl/postnl-magento2#297] opened 2022-04-01 14:32 UTC
**To Reproduce**
1. Add some items to your cart and visit the (Magento 2 default) checkout (/checkout).
2. Click on the PostNL shipping method and click "Pickup". Select one of the available pickup points.
3. Move on to the payment step. Click on one of the available payment methods. Now refresh the page to visit the payment step again (or click the logo in the header to visit the homepage and click the back button in the browser).

**Expected result**
All the data I have entered (e.g. address) and selections (selected shipping and payment method) I have made are still there.

**Actual result**
All the data is still there except the selected pickup point. If I would continue, the package will be sent to the entered shipping address instead of the previously selected pickup address.

**Workaround**
Go back to the shipping step and re-select the desired pickup location.

**Please complete the following information**

- Magento version: reproduced the issue in both 2.4.1 and 2.4.3p1
- PHP version: both 7.3 and 7.4
- TIG PostNL version: 1.10.1

**Comment by tig-jeffreybranderhorst** [comment] 2022-04-04 10:52
Hi @simonjanguapa,

Thank you for submitting this with the step to reproduce it. Because of the steps I was able to reproduce it and will place it on our backlog to fix.  Thank you again for submitting this! 

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment] 2022-08-04 08:09
Hi @simonjanguapa ,

We have released a new version of the extension, in this new version there is a fix for this issue. 
If you come across other issues, you can always contact us! 

Have a great day,
Jeffrey

**Closed by tig-jeffreybranderhorst** 2022-08-04 08:09 UTC
Labels: verified bug
