### ISSUE TITLE
[BUG] Invalid parameter configuration provided for $file argument of TIG\PostNL\Service\Pdf\Fpdi

### ISSUE THREAD

**Issue by rvanwilgen** [tig-nl/postnl-magento2#229] opened 2021-02-01 13:38 UTC
**To Reproduce**
1. Go to a shipment to generate a PostNL Label, 

**Expected result**
A pdf label for the generated shipment.

**Actual result**
Generates an exception error when clicking on the PostNL - Generate Label button. This also applies to the mass action part for shipments.
Looks like vendor/tig/postnl-magento2/Service/Pdf/FpdiFactory.php gives a String to the constructor of Fdpi class, instead it needs to be an instance of TIG\PostNL\Service\Shipment\Label\File.

<img width="1440" alt="postnl-error-stacktrace" src="https://user-images.githubusercontent.com/1614922/106465334-1f6e5e00-649a-11eb-86ba-f4cbacbb1941.png">

**Workaround**
None

** Please complete the following information**
- Magento version: 2.3.5-p1
- PHP version: 7.3.22
- TIG PostNL version: 1.9.5

**Comment by tig-jeffreybranderhorst** [comment] 2021-02-02 07:23
Hi @rvanwilgen 

Thank you for submitting this, we will investigate this and discuss it with the team. 

Have great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment] 2021-02-03 09:05
Hi @rvanwilgen 

I tried to reproduce this issue on a clean magento 2.3.5p1, but was not able to reproduce it. Could you send us a mail to support@tig.nl, so we can assist you with this issue. 

Have a great day,
Jeffrey

**Comment by piuga** [comment] 2021-02-04 14:22
Hi,

I also have this issue (Magento 2.3.6 and TIG PostNL 1.9.6) and the fix was to adjust
\TIG\PostNL\Service\Pdf\FpdiFactory :: constructTCPDF() function
the line 
`'file' => File::class,`
was replaced with
`'file' => $this->file,`

I hope this is useful to make a permanent fix.

**Comment by rvanwilgen** [comment] 2021-02-09 11:37
When installing the PostNL module on a clean install of 2.3.5-p1 and 2.4.2 everything works fine. 
So we did some further investigation and when we installed the Fooman Pdf Customiser M2 module on a clean install of 2.3.5-p1 and 2.4.2 with the PostNL module, the error came back.

I hope this helps in diagnosing the problem.

**Comment by tdgroot** [comment] 2021-02-11 09:18
@tig-jeffreybranderhorst It is reproducible when Fooman_PdfCustomiser is installed. The bug being is indeed fixed by the patch provided by @piuga.

**Comment by tig-jeffreybranderhorst** [comment] 2021-02-11 10:24
Hey @piuga @rvanwilgen @tdgroot ,

Thank you all for the messages and pull requests. We will test it and add the provided fix, thank you all again for helping us making the extension even better!

Have a great day,
Jeffrey

**Closed** 2021-06-09 10:42 UTC
Labels: fixed
