### ISSUE TITLE
[BUG] Previous Evening additional Shipping fee was still included after change country

### ISSUE THREAD

**Issue by fu4d** [tig-nl/postnl-magento2#180] opened 2020-06-08 06:58 UTC
Please help to fix the following issue.
We use PostNL to deliver product to Netherlands and the other Europe countries. But after we selected evening delivery option for Netherlands then we change to the others, we still got additional evening shipping fee. 

**To Reproduce**
1. Select product
2. Go to checkout page
3. Select your Netherlands shipping address or complete new shipping form with Netherlands country
![image](https://user-images.githubusercontent.com/6572288/83998767-e118b180-a993-11ea-8e17-472471827020.png)

4. Choose any evening delivery options then click Next.
![image](https://user-images.githubusercontent.com/6572288/83998891-2dfc8800-a994-11ea-8dc1-9fa7f3d9dbc5.png)

5. We will get PostNL Shipping fee with additional service (evening) fee.
![image](https://user-images.githubusercontent.com/6572288/83999121-ac592a00-a994-11ea-90bc-3352aa619a8d.png)

6. Go back to previous step then change your shipping address country (eg: Austria, with EUR 10) then click Next
![image](https://user-images.githubusercontent.com/6572288/83999903-466da200-a996-11ea-816e-dfdea07f3002.png)

7. We will see in summary checkout page PostHL shiping Fee still included additional (EUR 2) evening shipping fee
![image](https://user-images.githubusercontent.com/6572288/84001229-c4cb4380-a998-11ea-8b50-ef457f01c070.png)

**Expected result**
Shipping Fee will be updated always after we change delivery/pickup options or change destination/shipping address (Shipping fee should be EUR 10)

**Actual result**
Additional shipping fee still included (if we selected before) after address changing 

** Environment**
- Magento version: 2.3.3
- PHP version: 7.3.18
- TIG PostNL version: 1.9.0.1

**Comment by tig-jaspersmits** [comment] 2020-06-08 07:41
Hi @fu4d ,

Thanks for letting us know. I've been able to reproduce this and have placed this on our backlog. We will work on a solution and release it in an upcoming release.

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment] 2020-11-10 14:42
As far as I'm aware this should be fixed.
If that's not the case, feel free to reopen the issue.


Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment] 2020-11-11 09:38
I have reopened this one because I thought we released this. But this was such a major change we had to postpone it.
Keep an eye on the release notes here: https://docs.tig.nl/x/3YSC
I'll also give you an update here once I have more information about the release.

Kind regards,
Jasper
TIG

**Comment by tig-jeffreybranderhorst** [comment] 2021-03-04 11:30
Hi @fu4d ,

This should be fixed in the newest version of the postnl extension, if you update this problem will be fixed. If you still are having problems don't hesitate to contact us at support@tig.nl

Have a nice day,
Jeffrey

**Closed by tig-jeffreybranderhorst** 2021-03-04 11:30 UTC
Labels: on backlog
