### ISSUE TITLE
Issue with latest 1.7^ version using Magento 2.3

### ISSUE THREAD

**Issue by MichielTG** [tig-nl/postnl-magento2#87] opened 2019-01-09 11:30 UTC
After installing version 1.7 using composer, the bulk action button is not giving any options.

-> Using Magento 2.3.

![schermafbeelding 2019-01-09 om 12 29 36](https://user-images.githubusercontent.com/46106706/50896740-4caac800-140a-11e9-8cfa-6cdc5f9366a2.png)

![schermafbeelding 2019-01-09 om 12 31 44](https://user-images.githubusercontent.com/46106706/50896834-8bd91900-140a-11e9-936d-fdeb7f58760e.png)

**Comment by tig-rikjonkmans** [comment] 2019-01-09 13:40
Hi @MichielTG 
This looks like invalid static content. I advice to run bin/magento setup:static-content:deploy.

**Comment by MichielTG** [comment] 2019-01-09 14:34
I fixed the problem. For some reason this error happend when the account settings are not configured in the shopping configuration. So this problem occurs on a fresh installtion without configuring any settings.

**Comment by tig-rikjonkmans** [comment] 2019-01-09 14:48
@MichielTG ,

Seems like this is an acl issue, but good to hear it is fixed for now. I will look further into this, thank you for informing us about this issue.

**Comment by tig-rikjonkmans** [comment] 2019-01-11 12:59
@MichielTG, 
By shopping configuration, do you mean the account settings in the PostNL config tab "General configuration and account information" or something else ?

**Comment by MichielTG** [comment] 2019-01-11 16:57
It seems to occur when this setting is put to off.
![schermafbeelding 2019-01-11 om 17 57 13](https://user-images.githubusercontent.com/46106706/51048103-6a269000-15ca-11e9-9617-0afd6c8b377d.png)

**Comment by tig-dennisvanderhammen** [comment] 2019-01-14 15:57
Hi @MichielTG,

It seems that there is an extension conflict within the Temando Shipping extension and the PostNL extension. The Temando Shipping extension is automatically installed with Magento 2. When I disabled the extension, the errors seem to be gone. The cause seems to be the "Batch process" functionality that is added in the mass actions. This one is at the very bottom.

When the PostNL extension is disabled, we remove our options from the list, but somehow Magento seems to look for the highest index in the mass actions, and expect labels for every index in between.

Possible workarounds currently available:
1. Disable Temando Shipping
2. Set the PostNL modus to 'Test' or 'On'

We will include a fix for this issue in an upcoming release.

**Comment by MichielTG** [comment] 2019-01-16 14:57
Nice, good job!

**Comment by tig-rikjonkmans** [comment] 2019-01-21 12:05
Version 1.7.1 is released which contains a fix for this issue.

**Closed by tig-rikjonkmans** 2019-01-21 12:05 UTC
