### ISSUE TITLE
[BUG] Changing a Shipping Address doesn't update the label

### ISSUE THREAD

**Issue by Hexmage** [tig-nl/postnl-magento2#289] opened 2022-01-24 11:11 UTC
**To Reproduce**
Print a label
Change the shipping address
Print the same label again.

**Expected result**
The new label has the new shipping address.

**Actual result**
The new label has the old shipping address.

**Workaround**
None

** Please complete the following information**
- Magento version: 2.3.6-p1
- PHP version: 7.3.31
- TIG PostNL version: 1.10.0

**Comment by tig-jeffreybranderhorst** [comment] 2022-01-24 12:34
Hi @Hexmage,

We save the label in the database and the code first checks if there is already a label for this order and if the answer here is yes it will get the label out of the database instead of generating a new one to save resources. In your case, you should go into the shipment and press the button "cancel confirmation" and then change the address. If you then generate a label, it will make a new label with the correct address. 

Have a great day,
Jeffrey

**Comment by Hexmage** [comment] 2022-01-24 13:19
@tig-jeffreybranderhorst 
Looks like the label is not deleted if the confirmation is reverted.

**Comment by Hexmage** [comment] 2022-01-24 13:24
@tig-jeffreybranderhorst 
Correction, it does look like the old label is deleted correctly. It is just regenerated with the wrong address info.

**Comment by Hexmage** [comment] 2022-01-24 13:51
@tig-jeffreybranderhorst 
I figured out what the real issue was. The order was of the type PG. Which does some magic with the shipping addresses. Give the order 2 shipping addresses. But in this scenario the one on the label is no longer changeable.

**Comment by tig-jeffreybranderhorst** [comment] 2022-01-24 14:43
Hi @Hexmage,

Can you give me the steps to reproduce this with PG? Then I will try to reproduce this on our test sites aswell! 

Have a great day,
Jeffrey

**Comment by Hexmage** [comment] 2022-01-24 14:53
@tig-jeffreybranderhorst 
I sadly have no idea if this occurs for every PG order. 

But I do know what is going wrong.

In `\TIG\PostNL\Model\Shipment::getShippingAddress`, the `$postNLOrder->getPgOrderAddressId();` is the shipping address you see in the backend and the one you can modify by changing the shipping address. But the `$this->filterShippingAddress([$pgOrderAddressId,$orderBillingId], $pgAddressStreet);` function filters this one and picks up the other shipping address assigned to this order which you can not see in the backend. This second shipping address is used on the label.

**Comment by Hexmage** [comment] 2022-01-24 16:22
It turns out the order was originally placed as a pick up point but later changed to a normal shipping order. Which caused the issues with being unable to change the address on the shipping label.

**Comment by tig-jeffreybranderhorst** [comment] 2022-01-26 09:25
Hi @Hexmage,

Can you reproduce it now? If you can reproduce it, could you give us the steps to reproduce it?
Is it just a pick point order and then change it to a normal order? Or do we need to make a label first and then change?  

Have a great day,
Jeffrey

**Comment by tig-vincentthart** [comment] 2022-06-15 12:56
Hi @Hexmage ,

Because we did not receive an update on this ticket we will close it. 

If you have any follow up questions, feel free to contact PostNL on [digitaleklantsupport@postnl.nl](mailto:digitaleklantsupport@postnl.nl)

Have a nice day!
Vincent

**Closed as completed by tig-vincentthart** 2022-06-15 12:56 UTC
Labels: to be tested
