### ISSUE TITLE
[BUG] Shipping adres does not contain house number when payment status is not "Completed".

### ISSUE THREAD

**Issue by Batao-Ecommerce** [tig-nl/postnl-magento2#321] opened 2022-07-06 09:40 UTC
1. Add product to cart
2. Go to checkout
3. Fill in required fields
4. Place order
5. Use test mode of MultiSafePay
6.  When using Complete the "Expected result" happen.
     When using any other status the "Actual result" happen.

Now we have customers were the "Actual result" happens when they made an order.

**Expected result**
Order keeps house number after the transaction is not completed, open completed, declined, cancelled
![Schermafbeelding 2022-07-06 om 11 14 44](https://user-images.githubusercontent.com/108793487/177515809-90d22c3d-ff06-41bd-bc08-a90e170863d6.png)

**Actual result**
Order does not contain house number after the transaction is not completed, open completed, declined, cancelled. But the order is already created in magento.
![Schermafbeelding 2022-07-06 om 11 01 11](https://user-images.githubusercontent.com/108793487/177515832-c9a03191-9ee3-41b8-9d5e-98b759f3501a.png)

** Please complete the following information**
- Magento version: 2.4.3
- PHP version: 7.4
- TIG PostNL version: 1.12.0
- MultiSafePay version: 2.16
- Mageplaza OSC version: 4.1.0

**Comment by tig-jeffreybranderhorst** [comment] 2022-07-06 11:11
Hi @Batao-Ecommerce,

I cannot reproduce this on default magento checkout, and at this moment, PostNL is not compatible with One step checkouts. I suggest you contact PostNL at digitaleklantsupport@postnl.nl to ask them to support this one step checkout so we can make it compatible.

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment] 2022-07-15 13:08
Hi @Batao-Ecommerce ,

Because we could not reproduce it, I will close this issue on github.  If wish that your one step checkout need to be compatible, we suggest you contact PostNL via digitaleklantsupport@postnl.nl

Have a great day,
Jeffrey

**Closed by tig-jeffreybranderhorst** 2022-07-15 13:08 UTC
