### ISSUE TITLE
[QUESTION] Please summarize your question here

### ISSUE THREAD

**Issue by mgroensmit** [tig-nl/postnl-magento2#195] opened 2020-08-13 06:40 UTC
**Question**
From the shipment form it is possible to change the Parcel Count after a confirmation has been cancelled. However, it is still possible to change the Parcel Count from the order grid.

Why is it impossible to change the Parcel Count from the shipment form page?

**Comment by tig-dennisvanderhammen** [comment] 2020-08-13 08:28
Hi @mgroensmit,

I was wondering what happens when you change a confirmation like this, and while testing this I noticed that after cancelling my confirmation, I was able to change the parcel count. For me, a button to change the parcel count appeared after cancelling the confirmation.

Is this not the case for you? If not, what PostNL version and what Magento version are you running?

![image](https://user-images.githubusercontent.com/23072926/90111919-9b8bb280-dd4f-11ea-8d8b-0704c94953d9.png)

**Comment by mgroensmit** [comment] 2020-08-13 12:47
> Hi @mgroensmit,
> 
> I was wondering what happens when you change a confirmation like this, and while testing this I noticed that after cancelling my confirmation, I was able to change the parcel count. For me, a button to change the parcel count appeared after cancelling the confirmation.
> 
> Is this not the case for you? If not, what PostNL version and what Magento version are you running?
> 
> ![image](https://user-images.githubusercontent.com/23072926/90111919-9b8bb280-dd4f-11ea-8d8b-0704c94953d9.png)

The button will only appear if the order is shipped to 'The Netherlands', not if it's shipped to Belgium (or probably any other nation). There is a check in the Tig\PostNL\Model\Shipment class in the 'canChangeParcelCount' that prevents this. However, changing the parcel count from the order grid seems to work just fine.

So either the check can be removed or changed to improve the customer experience, or in the case changing parcel counts shouldn't be allowed for Belgian orders, there needs to be a check in the order grid change parcel count.

**Comment by tig-dennisvanderhammen** [comment] 2020-08-13 13:01
Hi @mgroensmit ,
I think being able to change the parcel count from the order grid is unintended behaviour, but it might be the preferred behaviour.

I'll have to ask our contact within PostNL if they know why this check exists in the first place. I'll get back to you.

**Comment by tig-dennisvanderhammen** [comment] 2020-08-26 07:36
Hi @mgroensmit,

To give you a small update, our contact is still reaching out internally to see which of the behaviour is the accepted one. Once she'll get back to me I can give you an update.

**Comment by tig-dennisvanderhammen** [comment] 2020-09-16 12:09
Hi @mgroensmit ,

Our contact reached out to us with an update. We'll be removing a "country == 'NL'" check which hides the edit button for other countries. You can expect this to be changed in a future release.

**Comment by tig-jaspersmits** [comment] 2020-11-10 14:49
I will close this issue as it will be fixed with the new release.
If there is anything else feel free to reopen the issue or create a new one.

Kind regards,
Jasper
TIG

**Closed by tig-jaspersmits** 2020-11-10 14:49 UTC
Labels: on backlog, question
