### ISSUE TITLE
Checkout hangs after reload

### ISSUE THREAD

**Issue by albundy2** [tig-nl/postnl-magento2#219] opened 2020-11-12 22:07 UTC
We use Tig GLS and PostNL. Test in template Luma, Claue and Porto see below result after first time load of checkout and doing a refresh or leaving the page and go back to checkout again. We have the same problem in default onepage checkout, in amasty onestepcheckout and mageplaza onestepcheckout

Developer tools in browser is giving the following error:
fields.js:84 Uncaught TypeError: Cannot read property 'extension_attributes' of null

**To Reproduce**
1. Added product to shopping cart go to checkout
2. ctrl F5 or F5 to reload page

**Expected result**
Page to reload completly

**Actual result**
Page will show only the shopping bag. Address fields, shipping part and payment info is not loaded

**Workaround**
No work arround

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/15823253/99000823-2a1ff380-253a-11eb-9001-8506bc7aef45.jpg)

** Please complete the following information**
- Magento version: 2.3.5p1
- PHP version: 7.2.34
- TIG PostNL version: 1.9.5

**Comment by tig-jaspersmits** [comment] 2020-11-13 08:50
Hi @albundy2 ,

Thanks for using the template to submit. Where exactly do I reload the page? In the shopping cart? This is not really clear to me. And do I need to install both GLS and PostNL to test this?

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment] 2020-11-17 11:29
Hi @albundy2 could you please follow up on my question so I can test this?
Thanks in advance!

Kind regards,
Jasper
TIG

**Comment by albundy2** [comment] 2020-11-17 12:06
onepage checkout or onestepcheckout depending on what checkout form is used. I both cases the checkout page shows only part or no part of the checkout form and the loader is keeping spinning

**Comment by hans2103** [comment] 2020-11-25 14:07
Same issue here on test.onderdelenexpert.nl/onestepcheckout

**Comment by tig-jaspersmits** [comment] 2020-11-26 13:44
Hi @albundy2 and @hans2103 ,

I've just tested this with both GLS and PostNL installed. But, I'm still unable to reproduce this issue.
Also, when I check test.onderdelenexpert.nl/onestepcheckout the problem doesn't occur for me?

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment] 2020-11-26 13:57
@albundy2 and @hans2103 ,

Just had a short talk about this with someone from our team. They told me that it could be right that it's happening for you and they provided me with a fix.

File: **TIG/PostNL/view/frontend/web/js/view/form/fields.js**
Row: **84** 
Replace that line with: 

`                    if (optionsArray.billingAddress !== undefined && optionsArray.billingAddress.extension_attributes === undefined) {
`

This should solve the problem. Could you let me if it did?

Kind regards,
Jasper
TIG

**Comment by hans2103** [comment] 2020-11-26 13:59
> Hi @albundy2 and @hans2103 ,
> 
> I've just tested this with both GLS and PostNL installed. But, I'm still unable to reproduce this issue.
> Also, when I check test.onderdelenexpert.nl/onestepcheckout the problem doesn't occur for me?
> 
> Kind regards,
> Jasper
> TIG

Switched from MagePlaza OSC to Swissup Firecheckout in the meanwhile. Sorry for not updating the issue here. 
Thank you for the suggested fix.

**Comment by hans2103** [comment] 2020-11-26 14:00
> @albundy2 and @hans2103 ,
> 
> Just had a short talk about this with someone from our team. They told me that it could be right that it's happening for you and they provided me with a fix.
> 
> File: **TIG/PostNL/view/frontend/web/js/view/form/fields.js**
> Row: **84**
> Replace that line with:
> 
> ` if (optionsArray.billingAddress !== undefined && optionsArray.billingAddress.extension_attributes === undefined) {`
> 
> This should solve the problem. Could you let me if it did?
> 
> Kind regards,
> Jasper
> TIG

Will this be added in the upcoming release of TIG/PostNL?

**Comment by tig-jaspersmits** [comment] 2020-11-26 14:03
Hi @hans2103 ,

Yes! We will add this fix to the next release.

Kind regards,
Jasper
TIG

**Comment by tig-vincentthart** [comment] 2021-06-09 10:13
Hi @hans2103 and @albundy2,

As this was part of the 1.9.6 release I will close the issue.

Greetings,

Vincent

**Closed by tig-vincentthart** 2021-06-09 10:13 UTC
Labels: in progress
