### ISSUE TITLE
Cutoff time returns error [magento 2.3.0]

### ISSUE THREAD

**Issue by renehol** [tig-nl/postnl-magento2#111] opened 2019-05-16 13:33 UTC
## Please follow the guide below

- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like.
- We may ask some questions or ask you to provide addition information after you placed your request.

---

### Make sure you are using the *latest* version: https://tig.nl/postnl-magento-extensies/
Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG PostNL Magento extension.

---

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [x] Bug report (encountered problems with the TIG PostNL Magento extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

### If your issue contains security sensitive information
** If your issue may contain sensitive information, please send us an e-mail at security@tig.nl.**
- [x] This issue does not contain any security sensitive information

---

### If the purpose of your issue is a *feature request*
- As a *..certain type of user..* I’d like to *..describe what you want..* in order to *..write goal(s)..*
- Suggestions and background: 
  If you have ideas for the solution write them down here. Include images, a picture is more worth than 1,000 words. If none, remove this line.

### If the purpose of your issue is a *bug report*
**Please describe the precise steps to reproduce your issue:**
- 1. Enable cutofftime in postnl module
- 2. set time to somewhere in the past
- 3. place order
- 4. fill in address and wait for postnl delivery days

- Expected result
A list with day's to choose from for delivery

- Actual result (Please provide screenshots if applicable)
a php exception is being thrown in vendor/tig/postnl-magento2/Controller/DeliveryOptions/Timeframes.php:125
message: string(135) "DateTime::__construct(): Failed to parse time string (today 0:00am) at position 10 (a): The timezone could not be found in the database"

This results in a json error and no days to choose.
![Schermafbeelding 2019-05-16 om 15 30 17](https://user-images.githubusercontent.com/25588490/57857491-8a23c580-77ef-11e9-87a2-53fe79152319.png)

- Workaround (If available, otherwise just write "None")
None

### If the purpose of your issue is about anything else, please describe your issue here
- Explain your issue here

### TIG support

- Please ask your question in English to ensure that your issue can help other people internationally. Nevertheless we will respond in English.
- If you want support with installing the PostNL extension, please contact citservicedesk@postnl.nl for free support, or contact us directly at support@tig.nl for paid support plans.

**Comment by tig-jeffreybranderhorst** [comment] 2019-05-16 13:53
Hi,

Thank you for sending in your issue. We send the current date towards the PostNL servers. PostNL recognizes that the selected delivery date is in the past and gives this error as a response. We do show the "First possibility" fallback correctly.

Because this issue seems to be related to the PostNL API, and not our extension I will be closing this issue.
If you have any questions about the API of PostNL, we recommend getting in touch with PostNL or your account manager.

Best Regards,
Jeffrey Branderhorst

**Comment by renehol** [comment] 2019-05-16 14:11
Hi, 

Thank you for the response. But the code to calculate the date gives the error. It is a hard php exception.

If the cutoff time is set to 18:00, and a customer wants to place a error at 20:00, the shipping day should me +1, but it gives an php error and thus falls back on first possibility. Or am i missing something?

**Comment by tig-dennisvanderhammen** [comment] 2019-05-16 14:26
Hi @renehol,

If there's a hard PHP exception being thrown, could you please share this exception? As it seems to be missing in your issue description.

Thank you in advance!

**Comment by renehol** [comment] 2019-05-16 14:30
Hi, i add the exception

**Comment by tig-dennisvanderhammen** [comment] 2019-05-16 14:51
Thank you! It could still be that it's PostNL's servers that isn't accepting the date, but even if that's the case, we shouldn't have any PHP exceptions thrown. We'll try to reproduce this and we will get back to you if we are able to reproduce it or if we have any more questions.

**Comment by tig-daanvandenbergh** [comment] 2019-05-20 06:33
@renehol,

The error mentions that more information is available in the logs. Could you share this information here? (If it contains sensitive data you can either anonymise it and share it here, or share it with us via e-mail at support@tig.nl mentioning this Github issue no.)

**Comment by kaybeudeker** [comment] 2019-05-20 20:00
Same issue here...

<img width="850" alt="Schermafbeelding 2019-05-20 om 21 57 40" src="https://user-images.githubusercontent.com/31165120/58048236-917a0480-7b4a-11e9-89c8-e77d4c24ec85.png">

**Comment by kaybeudeker** [comment] 2019-05-20 20:47
When trying to place the order, 500 error:

<img width="1432" alt="Schermafbeelding 2019-05-20 om 22 46 29" src="https://user-images.githubusercontent.com/31165120/58050968-2849bf80-7b51-11e9-92fc-eb013b0ac34d.png">

**Comment by tig-dennisvanderhammen** [comment] 2019-05-21 11:02
@kaybeudeker, it seems that you are experiencing a different error. Also, as far as I know, we don't do much in Magento's guest-payment-information call, which also seems to go wrong.

Could you either create a new issue or contact us on support@tig.nl? Could you please include whether you are using the PostNL address check and if you are using a 3rd party checkout extension or not (and if yes, which one)?

@renehol, I have the feeling that something might be going wrong in the locale selection. If you open up Stores->Configuration->General->Locale Options, what do you currently have selected as locale and timezone?

**Comment by renehol** [comment] 2019-06-06 06:12
@tig-dennisvanderhammen -> here are the settings for Locale
Timezone: Central Europe Standard Time (Europe Amsterdam)
Local: Dutch
Weight unit: kgs
First day of week: Sunday
Weekend Days: Sunday - Saturday

**Comment by tig-dennisvanderhammen** [comment] 2019-06-06 12:17
Hi @renehol,

Thank you. The error you encountered also occurs when the Timezone is not set to CEST. It seems that your environment is set up properly in that regard.

Considering that we are unable to reproduce this problem, could you please contact us on support@tig.nl as well? If you have a staging environment, could you also provide us with access to this environment?

**Closed by tig-dennisvanderhammen** 2019-06-06 12:17 UTC

**Comment by renehol** [comment] 2019-06-06 12:25
Hi @tig-dennisvanderhammen 

Did you test with php 7.2.15 & magento 2.3.0?
