### ISSUE TITLE
Delivery selection is mostly not working correct in 1.7.4

### ISSUE THREAD

**Issue by richardreen** [tig-nl/postnl-magento2#104] opened 2019-04-13 15:26 UTC
We are using magento 2.3.0 and tig/postnl module 1.7.4.
After upgrading to the 1.7.4 version the customer can sometimes choose a day for dellivery. But mostly there is only one option. See the images below for more information

![Screenshot_20190413_171657](https://user-images.githubusercontent.com/18627705/56081729-c50d9480-5e10-11e9-82a3-4f1695027e0d.png)
![Screenshot_20190413_171724](https://user-images.githubusercontent.com/18627705/56081731-c9d24880-5e10-11e9-9755-7d2e26a5f098.png)

The option choosing a postnl delivery point is working always correct.

Did talk to the customer service of postnl and when they checked there was no problem.
But today the problem is back again!!

We have configured 7 days that the customer can choose from.

**Comment by tig-daanvandenbergh** [comment] 2019-04-17 09:30
@richardreen,

This might be due to something in your configuration. Could you share with me how you've configured the Shipping-section of the PostNL-extension? This might be relevant in finding out if this is due to a bug.

**Comment by richardreen** [comment] 2019-04-17 15:40
A screenprint of the shipping section

![afbeelding](https://user-images.githubusercontent.com/18627705/56301310-d835a280-6137-11e9-8d42-3dfc6574737d.png)

**Comment by richardreen** [comment] 2019-04-20 15:55
In the meantime we were upgraded to magento 2.3.1 and this issue is also there...still facing the same problem but no progress in solving this issue. It is getting frustrating!!!!!

**Comment by tig-daanvandenbergh** [comment] 2019-04-23 10:54
Due to the holidays (Good Friday and Easter Monday) I wasn't able to respond to you as quickly as we usually do. I appreciate your patience. I'll get back to you ASAP.

**Comment by tig-daanvandenbergh** [comment] 2019-04-29 10:50
@richardreen, using the exact same configuration (also using Magento 2.3.1) I'm not able to reproduce this issue. Are you using other shipping plugins that might interfere with PostNL?

**Comment by richardreen** [comment] 2019-04-29 12:56
No we have not. But i have to mention also that for the last few days 
there were no issues on our side anymore so it looks like the problem 
was caused at the PostNL API side. They have solve it a few days ago and 
now it is working normal again.
We could close this ticket then~~



Daan van den Bergh schreef op 2019-04-29 12:50:

**Comment by tig-daanvandenbergh** [comment] 2019-04-29 13:10
Ah, that's good to hear, @richardreen.

Thanks for your reply. I will close this ticket.

**Closed by tig-daanvandenbergh** 2019-04-29 13:10 UTC
Labels: can't reproduce
