### ISSUE TITLE
SQL Query error

### ISSUE THREAD

**Issue by AleksZelenchuk** [tig-nl/postnl-magento2#66] opened 2018-08-20 11:58 UTC
Magento 2.2.4
I have installed this module on site and after some testing I found out that each of the PostNL massAction in order grid returns error.
Here is what happen when you choose "PostNL - Create shipments, print labels & confirm" option:
http://joxi.ru/eAOXaqVHxEJ8Pr

**Comment by tig-jeffreypeeters** [comment] 2018-08-20 13:50
Hey Aleks,

There is a known conflict with the Temando extension that could be causing this issue. Could you try disabling Temando and try the PostNL extension again?

We'll look into this further if it turns out that this is not the cause of your issue.

Kind Regards,
Jeffrey Peeters

TIG

**Comment by AleksZelenchuk** [comment] 2018-08-20 14:18
Hi tig-jeffreypeeters, 
I have turned off Temando as you said but nothing have changed. i'm still experiencing the same error.
Note: when I create shipping for single order it is working fine. So the problem is only with massactions.

**Comment by tig-jeffreypeeters** [comment] 2018-08-20 14:26
Hey Aleks,

Did you flush the cache before you tried the PostNL extension again? You can check whether or not you've correctly flushed your cache by looking at your logs again to see if the errors still contain "Temando" in them. If they do contain "Temando" you probably didn't disable the Temando extension correctly.

Could you send us your new logs if your issue persists after disabling Temando?

**Comment by AleksZelenchuk** [comment] 2018-08-20 14:37
I'm testing in on localhost without cache. And I think I've found a root of error: you need a very correct post code entered in address field. At least after that I'm not experiencing that horrible SQL error exception.
By the way isn't it better to not display that error but show only error message like with addError and write that only to log file? 
It looks really horrible to those who are not familiar with code (managers for example).

**Comment by tig-jeffreypeeters** [comment] 2018-08-27 11:52
Hey Aleks,

I've created a item on our backlog for you and we'll be investigating your issue further. I'll keep you posted about any progress we make on the issue.

Kind Regards,
Jeffrey Peeters

TIG

**Comment by WebWeave** [comment] 2018-08-29 18:18
We are having this issue aswell with Magento 2.2.5

**Comment by tig-jeffreypeeters** [comment] 2018-08-30 06:41
Hey @WebWeave,

Thank you for informing us. I'll make a note of this so if this question is asked again I can point to this solution.

Kind regards,
Jeffrey Peeters

TIG

**Comment by tig-jeffreypeeters** [comment] 2018-08-30 06:43
Hey @AleksZelenchuk,

Could you try the solution @WebWeave provided and then try the PostNL extension again? 

Kind regards,
Jeffrey Peeters
TIG

**Comment by AleksZelenchuk** [comment] 2018-08-30 07:14
Hi @tig-jeffreypeeters,
I have removed module but now after running any magento command I'm getting this error
`"Circular dependency: Magento\Framework\ObjectManager\Config\Reader\Dom depends on Magento\Framework\ObjectManager\Config\Reader\Dom and vice versa"`
I think this can be conflict with other module.
Is there some known issues with magento native or third party extensions?

**Comment by tig-jeffreypeeters** [comment] 2018-08-30 08:12
Hey @AleksZelenchuk,

The error doesn't look familiar to our developers. If we happen to come across a solution we'll let you know but we won't be investigating this issue further.

One thing you could try is disabling extensions that could provide a conflict to see if anything changes.

Kind regards,
Jeffrey Peeters

TIG

**Comment by AleksZelenchuk** [comment] 2018-08-30 08:16
Thanks @tig-jeffreypeeters 
I'll try to turn off some third party extensions one by one to check if some of them. If I find something I'll let you know.

**Comment by tig-jeffreypeeters** [comment] 2018-09-21 09:57
Hey @AleksZelenchuk ,

Did you manage to resolve your issue?

It has been almost a month since the last reply so I'll be closing this issue. If you haven't solved the issue I'll repopen it.

Kind regards,
Jeffrey Peeters

TIG

**Closed by tig-jeffreypeeters** 2018-09-21 09:57 UTC
