### ISSUE TITLE
[BUG] Failed to load the "TIG_PostNL/js/grid/toolbar" component when admin language is NL

### ISSUE THREAD

**Issue by jordy2607** [tig-nl/postnl-magento2#231] opened 2021-02-10 13:59 UTC
Sales admin grids have an issue loading the toolbar component when the admin language is set to NL (and possible other languages). When the language is set to the default en_US it is working as intended.

This error occurred after updating from 1.9.3 to 1.9.6 

**To Reproduce**
1. Set Admin account settings Interface Locale to Dutch
2. Go to Sales -> Order Grid

**Expected result**
Sales order grid page is shown with filter/search/pagination/post nl toolbar etc above the grid.

**Actual result**
Sales order grid page is shown without filter/search/pagination/post nl toolbar etc above the grid.

**Workaround**
Set Admin language to en_US

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/29774091/107526128-ce581b80-6bb7-11eb-83e2-bcf3f28b3d77.jpg)

**Please complete the following information**
 - Magento version: 2.3.6
 - PHP version: 7.3
 - TIG PostNL version: 1.9.6

**Comment by tig-jeffreybranderhorst** [comment] 2021-02-10 14:41
Hi @jordy2607 

First I want to thank you for submitting this, we have not heard this one before but we will investigate this. After our investigation we will update you on github!

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment] 2021-02-11 08:55
Hi @jordy2607 ,

We have tested this on a clean Magento 2.3.6 with PostNL and a Dutch language pack. We could not reproduce this problem, could you contact us on support@tig.nl, so we can support your issue further?

Have a great day,
Jeffrey

**Comment by tig-vincentthart** [comment] 2021-06-09 09:55
Hi @jordy2607,

Because we could not reproduce this issue, we will close it. 
If you need help with your setup, feel free to contact the support team.

Have a nice day!

Greetings

Vincent

**Closed by tig-vincentthart** 2021-06-09 09:55 UTC
