### ISSUE TITLE
Pick-up point address still used after selecting Home delivery

### ISSUE THREAD

**Issue by kozie** [tig-nl/postnl-magento2#102] opened 2019-04-11 19:52 UTC
### Make sure you are using the *latest* version: https://tig.nl/postnl-magento-extensies/
Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG PostNL Magento extension.

---

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [x] Bug report (encountered problems with the TIG PostNL Magento extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

### If your issue contains security sensitive information
** If your issue may contain sensitive information, please send us an e-mail at security@tig.nl.**
- [x] This issue does not contain any security sensitive information

---

**Please describe the precise steps to reproduce your issue:**
- Disable "delivery days" option, enable "Pick-up points".
- Choose a pick-up point in the check-out process
- Immediately choose 'Home delivery'
- Place order

**Expected results**
Order with customer's address information

**Actual results**
Order with Pick-up address information

**Possible issue**
Choosing a pick-up point does an XHR request with a save. In this save, the correct address data is set within the quote.
Choosing the option 'Home delivery' does not update this information thus won't remove the pick-up point address information from the quote.
Selecting a shipping day (with the aforementioned option "Delivery days" enabled) does indeed call the same save endpoint as the pick-up options does. This will also remove address information (which i expect that 'Home delivery' would do also)

**Comment by tig-jeffreybranderhorst** [comment] 2019-04-12 13:17
Hey @kozie,

Thank you for submitting this issue.  I can reproduce this with your steps so i made a backlog item for this issue. We will try to make a fix for this as soon as possible. 

If you wanna know the progress of the issue you could contact us and ask for the status of POSTNLM2-795

Best regards,
Jeffrey

**Comment by tig-daanvandenbergh** [comment] 2019-04-30 18:12
@kozie,

We've did some testing and it appears this is not a bug, but actually a matter of user experience and furthermore desired behaviour. 

Whenever one of the tabs is selected (either Home Delivery or Pick-up points) the visual cues are strong enough for a customer to be triggered to make a selection from the list. In our opinion: automatically making a choice (when only one choice is available, as you depict in this issue) could work counter intuitive in other situations. 

This is why we decided to not make any changes to the current user experience. I'm closing this issue.

**Comment by kozie** [comment] 2019-04-30 18:26
I think you misunderstood the current situation. The issue describes addresses from pick-up points being used for the actual orders altough home-delivery has been selected afterwards. It feels to me you describe an issue/feature in UX context just on the frontend and not about address information for orders.
Please consider reopening the current issue or reviewing it again.

Could you be more specific on your test case otherwise.

**Comment by tig-daanvandenbergh** [comment] 2019-05-01 06:33
Oh, after some further testing I see what you mean. It wasn't clear to me that the shipping address is actually saved within the order. I'll reopen the issue and work on a fix.

Thanks for your prompt response!

**Comment by tig-daanvandenbergh** [comment] 2019-05-02 08:26
Hi @kozie,

I've created a fix for this which will be included in the next release.

I'm closing this issue. Thanks again for the report!

**Closed by tig-daanvandenbergh** 2019-05-02 08:26 UTC
Labels: on backlog, verified bug

**Comment by Goeny** [comment] 2020-02-21 09:28
We have an issue which is possibly related to this.

When a customer places an order and selects "Pick-Up" the shipping address does change to the pickup location and the shipping labels are correctly printed etc.. However, the email with Track&Trace information tells the customer that the package will be delivered at the Invoice address.
