### ISSUE TITLE
Undefined index: actions in vendor/tig/postnl-magento2/Plugin/Admin/Ui/Component/MassAction.php on line 67

### ISSUE THREAD

**Issue by patvdleer** [tig-nl/postnl-magento2#90] opened 2019-01-21 13:41 UTC
### Make sure you are using the *latest* version: https://tig.nl/postnl-magento-extensies/
Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG PostNL Magento extension.

---

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [x] Bug report (encountered problems with the TIG PostNL Magento extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

## Version

Magento CE v2.3.0
tig/PostNL v1.7

## Bug

In admin,  while trying to open the admin -> stores -> inventory -> source

url: /admin_xxx/inventory/source/index/key/XXX/

```
1 exception(s):
Exception #0 (Exception): Notice: Undefined index: actions in vendor/tig/postnl-magento2/Plugin/Admin/Ui/Component/MassAction.php on line 67

Exception #0 (Exception): Notice: Undefined index: actions in vendor/tig/postnl-magento2/Plugin/Admin/Ui/Component/MassAction.php on line 67
#0 vendor/tig/postnl-magento2/Plugin/Admin/Ui/Component/MassAction.php(67): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/var/www/vhosts...', 67, Array)
#1 vendor/magento/framework/Interception/Interceptor.php(146): TIG\PostNL\Plugin\Admin\Ui\Component\MassAction->afterPrepare(Object(Magento\Ui\Component\MassAction\Interceptor), NULL)
#2 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Ui\Component\MassAction\Interceptor->Magento\Framework\Interception\{closure}()
#3 generated/code/Magento/Ui/Component/MassAction/Interceptor.php(26): Magento\Ui\Component\MassAction\Interceptor->___callPlugins('prepare', Array, Array)
#4 vendor/magento/framework/View/Layout/Generator/UiComponent.php(164): Magento\Ui\Component\MassAction\Interceptor->prepare()
#5 vendor/magento/framework/View/Layout/Generator/UiComponent.php(161): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\MassAction\Interceptor))
#6 vendor/magento/framework/View/Layout/Generator/UiComponent.php(161): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Container))
#7 vendor/magento/framework/View/Layout/Generator/UiComponent.php(142): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Listing))
#8 vendor/magento/framework/View/Layout/Generator/UiComponent.php(102): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'inventory_sourc...', Array, Object(Magento\Framework\View\Layout\Interceptor))
#9 vendor/magento/framework/View/Layout/GeneratorPool.php(81): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#10 vendor/magento/framework/View/Layout.php(343): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#11 vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout->generateElements()
#12 vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#13 vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#14 vendor/magento/framework/View/Layout.php(253): Magento\Framework\View\Layout\Builder->build()
#15 vendor/magento/framework/View/Layout.php(875): Magento\Framework\View\Layout->build()
#16 vendor/magento/module-backend/Model/View/Result/Page.php(26): Magento\Framework\View\Layout->getBlock('menu')
#17 vendor/magento/module-inventory-admin-ui/Controller/Adminhtml/Source/Index.php(33): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Invento...')
#18 vendor/magento/framework/App/Action/Action.php(108): Magento\InventoryAdminUi\Controller\Adminhtml\Source\Index->execute()
#19 vendor/magento/module-backend/App/AbstractAction.php(231): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#20 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#21 vendor/magento/framework/Interception/Interceptor.php(138): Magento\InventoryAdminUi\Controller\Adminhtml\Source\Index\Interceptor->___callParent('dispatch', Array)
#22 vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\InventoryAdminUi\Controller\Adminhtml\Source\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#23 vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\InventoryAdminUi\Controller\Adminhtml\Source\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#24 vendor/magento/framework/Interception/Interceptor.php(153): Magento\InventoryAdminUi\Controller\Adminhtml\Source\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#25 generated/code/Magento/InventoryAdminUi/Controller/Adminhtml/Source/Index/Interceptor.php(26): Magento\InventoryAdminUi\Controller\Adminhtml\Source\Index\Interceptor->___callPlugins('dispatch', Array, NULL)
#26 vendor/magento/framework/App/FrontController.php(159): Magento\InventoryAdminUi\Controller\Adminhtml\Source\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#27 vendor/magento/framework/App/FrontController.php(99): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\InventoryAdminUi\Controller\Adminhtml\Source\Index\Interceptor))
#28 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#29 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#30 app/code/Infortis/Cgen/Plugin/Magento/Framework/App/FrontController.php(32): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#31 vendor/magento/framework/Interception/Interceptor.php(135): Infortis\Cgen\Plugin\Magento\Framework\App\FrontController->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#32 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#33 generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#34 vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#35 vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#36 index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#37 {main}
```

**Comment by tig-jeffreybranderhorst** [comment] 2019-01-21 15:25
Hi @patvdleer,

We can reproduce this issue, and we will fix it in a future version of the PostNL extension. This error only shows if the PostNL extension is set on "off"  on "test" or "live" the error should not be shown and the page should load in without issues. 

Met vriendelijke groet / Kind regards / Mit freundlichen Grüßen / 最好的祝福,

Jeffrey Branderhorst
CUSTOMER CARE SPECIALIST

**Comment by tig-daanvandenbergh** [comment] 2019-04-17 09:47
As this issue seems to be fixed in the latest release, I'm closing this issue.

**Closed by tig-daanvandenbergh** 2019-04-17 09:47 UTC
Labels: in progress, verified bug
