### ISSUE TITLE
[BUG] JS error when PostNL is disabled for other shops with Onestepcheckout

### ISSUE THREAD

**Issue by JoostWan** [tig-nl/postnl-magento2#226] opened 2021-01-08 21:31 UTC
**To Reproduce**
1. Go to onestepcheckout
2. Fill in address details
3. Wait for Magento to reload shipping info 

**Expected result**
No error

**Actual result**
Checkout hangs with a JS error

<img width="1059" alt="Screenshot 2021-01-08 at 22 17 43" src="https://user-images.githubusercontent.com/5435412/104065762-9f3d3b80-5200-11eb-937d-66ea6d596e1d.png">

In the last version there is a fix for onestepcheckout _POSTNLM2-1090 - Het huisnummer wordt nu correct getoond bij het order overzicht van verschillende 3rd party checkouts._

This is working fine when PostNL is enabled. But for a different store where PostNL is not used the JS file is still loaded and generates a error because `housenumberElement` and `housenumberAdditionElement` not exist.

**Comment by tig-jeffreybranderhorst** [comment] 2021-01-11 07:49
Hi @JoostWan ,

Thank you for submitting this, we will test this and make changes where needed.

**Comment by tig-jeffreybranderhorst** [comment] 2021-01-11 10:33
Hi @JoostWan,

Could you contact us at support@tig.nl so we can talk about this issue. We have some question because I cannot reproduce it instantly but we want to help you further and investigate it.

Have a great day,
Jeffrey

**Comment by tig-vincentthart** [comment] 2021-05-14 14:48
Hi @JoostWan,

As mentioned by our support team, this issue has been resolved with PostNL 1.9.7

**Closed by tig-vincentthart** 2021-05-14 14:48 UTC
