### ISSUE TITLE
Label for Germany partially rotated and cut off

### ISSUE THREAD

**Issue by evs-xsarus** [tig-nl/postnl-magento2#105] opened 2019-04-15 11:31 UTC
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG PostNL Magento extension.
- [x] Bug report (encountered problems with the TIG PostNL Magento extension)
- [x] This issue does not contain any security sensitive information

---
**Steps to reproduce this issue:**
- Step 1: go to shipments
- Step 2: open a shipment to Germany
- Step 3: click on 'Print label'
- Expected result
See right label in screenshot
- Actual result (Please provide screenshots if applicable)
See left label in screenshot
- Workaround (If available, otherwise just write "None")
None

![image](https://user-images.githubusercontent.com/44158071/56129483-7ed84280-5f82-11e9-8a13-56cb71afc824.png)

**Comment by tig-daanvandenbergh** [comment] 2019-04-17 09:24
@evs-xsarus,

I've tried to reproduce the issue, but failed. I've asked our PostNL representative for more information on this issue, to figure out whether this concerns a bug in the extension.

I'll keep you posted.

**Comment by tig-daanvandenbergh** [comment] 2019-04-17 10:46
@evs-xsarus,

We still cannot reproduce the issue. Could you send an e-mail to support@tig.nl and provide us with the address to which you are trying to send the package?

Please mention issue no. POSTNLM2-799 in your e-mail.

Thank you.

**Comment by evs-xsarus** [comment] 2019-04-29 09:05
@tig-bartrusschenberg I've sent the information on 17-4-2019 and am wondering if you have any information regarding this issue.

**Comment by tig-bartrusschenberg** [comment] 2019-04-29 09:52
@evs-xsarus 

Thanks for your response. We are currently trying to reproduce this issue.

Would you mind sending us the generated barcode – starting with 3S?
Please mention issue no. POSTNLM2-799 in your e-mail.

**Comment by evs-xsarus** [comment] 2019-04-29 09:59
@tig-daanvandenbergh the barcode is sent by mail as requested.

**Comment by tig-daanvandenbergh** [comment] 2019-04-29 12:47
Thank you, @evs-xsarus. I've received your 3S-code. Our PostNL representative will use the code to try and replicate the call. This way we can try and reproduce this issue.

**Comment by tig-daanvandenbergh** [comment] 2019-04-30 08:14
Hi @evs-xsarus,

I've figured out what the issue is.

The product code you're using for your EPS products is 4950. According to the PostNL dev-docs, this should be 4952, because 4950 is for businesses:

![image](https://user-images.githubusercontent.com/36000627/56947527-c4be0a80-6b2d-11e9-8da9-2b3f9bcc0d8d.png)

Are you sure you're using the latest version of the PostNL-extension? Because an erroneous default value of the configuration caused this 'mistake' in an earlier version and has been fixed in [this commit](https://github.com/tig-nl/postnl-magento2/commit/0c47da0b49948557d8eac1b5f6b504c3ab16524d) (feb 14th).

If you're using the latest version, you can still fix this by navigating to _Stores > Configuration > Sales > PostNL > Extra > PostNL settings > EPS and Belgium_ unchecking _'Use system value'_ and setting **Default EPS delivery** to _EU Pack Special Consumer_.

![image](https://user-images.githubusercontent.com/36000627/56948431-68101f00-6b30-11e9-9df5-6d7c0bb9395f.png)

After this you can navigate back to the order, click _Cancel_ (or _Change_, depending on your version of the extension) _Confirmation_. This will remove the generated label. After this you can re-generate the label, and it should now be generated as expected.

Could you let me know if this worked out for you?

**Comment by tig-daanvandenbergh** [comment] 2019-06-04 06:59
Since you haven't responded in over a month. I'm closing this issue.

**Closed by tig-daanvandenbergh** 2019-06-04 06:59 UTC
Labels: fixed

**Comment by evs-xsarus** [comment] 2019-06-04 07:00
@tig-daanvandenbergh sorry for not responding, I totally forgot about it. The fix you pointed out was indeed the one I needed.
