### ISSUE TITLE
Invalid Blocktype TIG\PostNL\Block\Sales\Order\Fee

### ISSUE THREAD

**Issue by SilvanLaroo** [tig-nl/postnl-magento2#2] opened 2017-05-04 11:31 UTC
Hi Tig,

We've installed your extension via composer. In the frontend, when we view an order as customer we get this error:
`TIG\PostNL\Block\Sales\Order\Fee`

The block is not available in the module.

**Comment by tig-berendlantink** [comment] 2017-05-05 14:20
Hi @SilvanLaroo,

Thanks for your feedback. We confirmed this issue and will fix it. 
Internal issue: POSTNLM2-232

**Comment by jghaanstra** [comment] 2017-05-15 20:49
Any news on when this will be fixed? This is a pretty bad one for user experience.

**Comment by tig-berendlantink** [comment] 2017-05-16 15:05
The issue is on our backlog and will be released together with some other issues.

**Comment by tig-berendlantink** [comment] 2017-05-26 07:24
@jghaanstra Fix is ready and we will release Monday version 1.1.3.

**Comment by tig-michielgerritsen** [comment] 2017-05-30 06:12
Hi @SilvanLaroo and @jghaanstra,

The 1.1.3 version of the extension is released yesterday. You can check the [release notes](https://confluence.tig.nl/display/TIGSD/Release+notes+van+de+PostNL+Magento+2+extensie) for more info. Updating the extension can be done by running:

``composer update tig/postnl-magento2``

**Closed by tig-michielgerritsen** 2017-05-30 06:12 UTC

**Comment by tig-martijndull** [comment] 2020-05-28 13:27
test
