### ISSUE TITLE
Sunday delivery

### ISSUE THREAD

**Issue by DylanHopman** [tig-nl/postnl-magento2#146] opened 2020-01-06 13:16 UTC
## Please follow the guide below

- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like.
- We may ask some questions or ask you to provide addition information after you placed your request.

---

### Make sure you are using the *latest* version: https://tig.nl/postnl-magento-extensies/
Issues with outdated version will be rejected.
- [ x ] I've **verified** and **I assure** that I'm running the latest version of the TIG PostNL Magento extension.

---

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [ x ] Bug report (encountered problems with the TIG PostNL Magento extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

### If your issue contains security sensitive information
** If your issue may contain sensitive information, please send us an e-mail at security@tig.nl.**
- [ x ] This issue does not contain any security sensitive information

---

### If the purpose of your issue is a *feature request*
- As a *..certain type of user..* I’d like to *..describe what you want..* in order to *..write goal(s)..*
- Suggestions and background: 
  If you have ideas for the solution write them down here. Include images, a picture is more worth than 1,000 words. If none, remove this line.

### If the purpose of your issue is a *bug report*
**Please describe the precise steps to reproduce your issue:**
- Step 1, Step 2, ...
- Expected result
- Actual result (Please provide screenshots if applicable)
- Workaround (If available, otherwise just write "None")

### If the purpose of your issue is about anything else, please describe your issue here
- Explain your issue here

### TIG support

- Please ask your question in English to ensure that your issue can help other people internationally. Nevertheless we will respond in English.
- If you want support with installing the PostNL extension, please contact citservicedesk@postnl.nl for free support, or contact us directly at support@tig.nl for paid support plans.

----------------------------------------

Hello,

We have a problem with your module. If we turn on all days for the shipment days, we will also see the Monday delivery. This is what we want. What we do not want is that the Sunday delivery starts. Because of this we have turned off the Sunday delivery option. This seems to be going well, but if it's Saturday, people can still opt for Sunday delivery.

To make the problem clearer, I have a number of screenshots for you that show it a bit better.

I hope you can come out of this.

Kind regards,
Dylan
![Schermafbeelding 2020-01-06 om 12 15 24](https://user-images.githubusercontent.com/43844828/71820337-19d3f800-308f-11ea-9783-88d32640913a.png)
![Schermafbeelding 2020-01-06 om 12 16 08](https://user-images.githubusercontent.com/43844828/71820338-1a6c8e80-308f-11ea-985b-30532b07b49d.png)
![Schermafbeelding 2020-01-06 om 12 15 44](https://user-images.githubusercontent.com/43844828/71820339-1a6c8e80-308f-11ea-8d91-a8f9e2468d55.png)

**Comment by tig-dennisvanderhammen** [comment] 2020-01-06 14:12
Hi @DylanHopman,

I have all shipping days enabled on my local environment, and Sunday delivery turned off. My local environment is currently set up as Saturday, and the next option I get is Monday, as intended, and just as shown in your screenshots.

What I'm suspecting is that people don't actually select a delivery option and only have PostNL selected. When no delivery option is selected, the extension assumes "The next possible moment".

I'll have to discuss this with the team so I've created a backlog item for this. In your case I see that PostNL is already selected. Could it be that PostNL is considered the "Default shipping option"? If so, to reduce the cases you might receive, maybe you can remove the default option, forcing the user to select a delivery option.

**Comment by DylanHopman** [comment] 2020-01-07 08:05
Hoi Dennis,

Hebben jullie al wat meer informatie voor mij?
Ik zag namelijk dat je gereageerd had en het nog even ging navragen. Maar verder nog niks vernomen.

Ik hoor het graag.


Met vriendelijke groet,


Dylan Hopman
Frontend Developer

De Hooge Krocht 2B
2201 TX Noordwijk

[signature_1159556744]
[signature_2076785600]
[signature_537655340]
[signature_1849448022]       [signature_1936863761]





Van: Dennis van der Hammen <notifications@github.com>
Beantwoorden - Aan: tig-nl/postnl-magento2 <reply@reply.github.com>
Datum: maandag 6 januari 2020 om 15:12
Aan: tig-nl/postnl-magento2 <postnl-magento2@noreply.github.com>
CC: Dylan Hopman <dylan@atvise.nl>, Mention <mention@noreply.github.com>
Onderwerp: Re: [tig-nl/postnl-magento2] Sunday delivery (#146)


Hi @DylanHopman<https://github.com/DylanHopman>,

I have all shipping days enabled on my local environment, and Sunday delivery turned off. My local environment is currently set up as Saturday, and the next option I get is Monday, as intended, and just as shown in your screenshots.

What I'm suspecting is that people don't actually select a delivery option and only have PostNL selected. When no delivery option is selected, the extension assumes "The next possible moment".

I'll have to discuss this with the team so I've created a backlog item for this. In your case I see that PostNL is already selected. Could it be that PostNL is considered the "Default shipping option"? If so, to reduce the cases you might receive, maybe you can remove the default option, forcing the user to select a delivery option.

**Comment by tig-dennisvanderhammen** [comment] 2020-01-07 08:37
Hi @DylanHopman,

As stated in my previous comment, PostNL decides the priority of backlog items. Considering I've only created the backlog item yesterday, I don't have any updates right now.

We'll get back to you on this Github issue once we have more information.

**Comment by tig-support** [comment] 2020-02-11 09:55
Note from Jen: Automatically assigned Jasper Smits to this issue as no one was assigned.

**Comment by tig-jeffreybranderhorst** [comment] 2021-03-03 14:03
Hi @DylanHopman ,

I see this issue is still open, we changed the postnl extension, Sunday is not connected with Monday anymore, so you can show Monday as shipping date and turn off Sunday. This should be fixed in the newest version of PostNL. Are you still having problems don't hesitate to contact us at support@tig.nl.

Have a nice day!
Jeffrey

**Closed by tig-jeffreybranderhorst** 2021-03-03 14:03 UTC
Labels: in progress, on backlog

**Comment by DylanHopman** [comment] 2021-03-04 08:23
Hoi Jeffrey,

Ik ga dit even nakijken 🙂


Met vriendelijke groet,

Dylan Hopman
Front-end Webdeveloper
[Atvise Online Resultaat]       Atvise - Online Resultaat
[https://www.atvise.nl/wp-content/uploads/email/Location-Pin.png] De Hooge Krocht 2B, 2201 TX Noordwijk
[https://www.atvise.nl/wp-content/uploads/email/Phone-Smart.png] 071 207 3400
[https://www.atvise.nl/wp-content/uploads/email/Web-Cursor.png] www.atvise.nl<https://www.atvise.nl/>
Volg ons op social media        [Atvise Facebook] <https://www.facebook.com/atvise/>    [Atvise LinkedIn] <https://www.linkedin.com/company/3085858/>


________________________________
Van: Jeffrey Branderhorst <notifications@github.com>
Verzonden: woensdag 3 maart 2021 15:04
Aan: tig-nl/postnl-magento2 <postnl-magento2@noreply.github.com>
CC: Dylan Hopman <dylan@atvise.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [tig-nl/postnl-magento2] Sunday delivery (#146)


Hi @DylanHopman<https://github.com/DylanHopman> ,

I see this issue is still open, we changed the postnl extension, Sunday is not connected with Monday anymore, so you can show Monday as shipping date and turn off Sunday. This should be fixed in the newest version of PostNL. Are you still having problems don't hesitate to contact us at support@tig.nl<mailto:support@tig.nl>.

Have a nice day!
Jeffrey
