### ISSUE TITLE
[BUG] House number/addition empty after failed payment

### ISSUE THREAD

**Issue by mlaurense** [tig-nl/postnl-magento2#283] opened 2021-12-10 10:06 UTC
**To Reproduce**
This is reproduced on a standard Magento 2.4.3-p1 install with only demo data, PostNL and MultiSafePay extensions installed.
1. Proceed to place an order, with address check enabled. After entering postcode and housenumber/addition (I used '2 C'), the street and city fields are automatically populated.
![Schermafbeelding 2021-12-10 om 10 55 09](https://user-images.githubusercontent.com/16759472/145555745-d5a9d356-7708-497b-a7e7-9695f7080a2e.png)
![Schermafbeelding 2021-12-10 om 10 55 30](https://user-images.githubusercontent.com/16759472/145555772-aef7eca3-e357-4ac9-8ca5-86627f564211.png)

2. Proceed to payment, and make sure the payment fails. E.g., use MultiSafePay in test mode, choose iDEAL, and cancel the payment.

3. When returning to the checkout, the housenumber/addition fields are now empty
![Schermafbeelding 2021-12-10 om 10 56 04](https://user-images.githubusercontent.com/16759472/145555799-95ab66ce-89cf-48d0-ba1d-6d3d0b61adab.png)
To clarify, I now entered '1 A'

4. The housenumber/addition fields are now duplicated:
![Schermafbeelding 2021-12-10 om 11 01 14](https://user-images.githubusercontent.com/16759472/145555904-57f8f3cf-10d0-4b8e-804d-a34c8d2a92bd.png)

**Expected result**
Housenumber/addition fields should be saved in the standard Magento address fields, and should have been filled when returning from a failed payment.

**Actual result**
Address is not correctly saved, due to non-standard housenumber/addition fields.

**Workaround**
None (yet).

** Please complete the following information**
- Magento version: 2.4.3-p1
- PHP version: 7.4
- TIG PostNL version: 1.10.0

**Comment by rbouma** [comment] 2021-12-10 10:12
We have the same issue with Magento 2.4.3 Please fix.

**Comment by mlaurense** [comment] 2021-12-10 10:16
Might be related to #274 ?

**Comment by tig-jeffreybranderhorst** [comment] 2021-12-10 12:55
Hi @mlaurense,

Thank you for submitting this issue, we will test this and place the bug on the backlog if we can reproduce it.  Thank you, for the clear steps to follow to reproduce it!

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment] 2021-12-13 08:30
Hi @mlaurense,

We have tried this internally with the same setup and can reproduce this behavior. Thank you for your step to step guide, this really helped to reproduce the error.

I've placed this issue on our Backlog and will keep you informed of the progress.

Have a great day,
Jeffrey

**Comment by ZIPITRO** [comment] 2022-03-01 08:15
Hi @tig-jeffreybranderhorst,

Any news on this reported bug? We also experience this, when the payment fails.

Thanks for your reply!
Have a good day!

Paul

**Comment by tig-jeffreybranderhorst** [comment] 2022-03-01 08:33
Hi @ZIPITRO,

This should be fixed in our next release. The complete release needs to be tested by PostNL and by us before releasing. When then are no issues found with testing, we will release this version at this moment I cannot say when the release will be. 

Have a great day,
Jeffrey

**Comment by ZIPITRO** [comment] 2022-03-01 09:20
> Hi @ZIPITRO,
> 
> This should be fixed in our next release. The complete release needs to be tested by PostNL and by us before releasing. When then are no issues found with testing, we will release this version. At this moment I cannot say when the release will be.
> 
> Have a great day, Jeffrey

Thanks Jeffrey!

**Comment by tig-jeffreybranderhorst** [comment] 2022-03-02 12:42
Hi @ZIPITRO, 

We discussed this internally, and we are expecting that with testing and then releasing it is going to take around 4 weeks. This is an estimation, so it could be longer if we find error while testing.  

Have a great day,
Jeffrey

**Comment by ZIPITRO** [comment] 2022-03-08 14:18
> Hi @ZIPITRO,
> 
> We discussed this internally, and we are expecting that with testing and then releasing it is going to take around 4 weeks. This is an estimation, so it could be longer if we find error while testing.
> 
> Have a great day, Jeffrey

That would be great! Thanks for discussing this internally!

Have a good day!

Paul

**Comment by tig-jeffreybranderhorst** [comment] 2022-03-17 13:14
Hi @ZIPITRO,

We don't have a direct workaround. However, I can give you the fix we made, the fix is still in test phase, so please be careful with it and test it first yourself. 
The fix needs to be added in view/frontend/web/js/view/billing-address-mixin.js 
The code is added after: 
`houseNumberAddition = attribute.value;
                        }
                    });`

The code that needs to be added is:
` if (quote.billingAddress().street[1] !== houseNumber) {
                        quote.billingAddress().street.splice(1,1);
                    }

                    if (quote.billingAddress().street[2] !== houseNumberAddition) {
                        quote.billingAddress().street.splice(1,1);
                    }`
                    
So afterward it should look like: 

![image](https://user-images.githubusercontent.com/23314965/158815564-cdc62856-800e-40ad-926f-154536ff77f7.png)

If there are questions, don't hesitate to contact us! 

Have a great day,
Jeffrey

**Comment by ZIPITRO** [comment] 2022-03-21 11:05
Hi Jeffrey,

Thanks, but I do not see any changes as in it *forgets* the house number after a failed payment, any other requirement like mimimum patch level / magento version?

**Comment by tig-jeffreybranderhorst** [comment] 2022-03-21 15:54
Hi @ZIPITRO,

Did you delete or regenerated your static content to let the new JS code be active? You could do this with bin/magento setup:static-content:deploy

Have a great day,
Jeffrey

**Comment by mlaurense** [comment] 2022-03-24 15:50
Hi @tig-jeffreybranderhorst 

This isn't even half fixed. Have you tested the scenario above?

When returning to the shop after failed payment, and entering the checkout again, the housenumber and addition fields are **empty**. When deliberately entering a different number as before, it shows it correct in the next step, but it is still incorrect in the sidebar:
![Schermafbeelding 2022-03-24 om 16 43 30](https://user-images.githubusercontent.com/16759472/159955277-577b8957-bf55-408e-8c8c-cb4b286872d4.png)

Because the housenumber and address fields are empty, we are experiencing the same problem as @ZIPITRO in our own checkout, as the failed payment redirects the user to the payment step, and the address is entered in the previous step, thus the user never gets to enter the housenumber/addition again. Also, it is highly unprofessional that the checkout 'forgets' the housenumber and addition. Why are you replacing the fields with your own tig_housenumber and tig_housenumber_addition, instead of using the standard street[1] and street[2]?

**Comment by tig-jeffreybranderhorst** [comment] 2022-03-28 12:54
Hi @mlaurense,

First of all, thank you for your feedback. 

“This isn't even half fixed. Have you tested the scenario above?” 

You are correct, the fix has not been tested yet as it is still on the backlog for Q/A as mentioned in my previous post, but I wanted to share with you the earliest code available. I was enthusiastic to share it with you. I will add your feedback to the issue and move the issue back to the open queue.  Thank you once more for your feedback.

“Why are you replacing the fields with your own tig_housenumber and tig_housenumber_addition, instead of using the standard street[1] and street[2]?“

Regarding  your question about the street addresses: We use our own fields because of the postcode checker of PostNL and the issues from customers in the past that used the default address fields differently. The PostNL postcode checker uses these fields to auto generate street names after filling in the postcode and house number. For compatibility reasons we have not changed this way of working.

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment] 2022-05-03 12:48
Hi @ZIPITRO,

Unfortunately, I cannot give you an update as of this moment. Our current focus is to release a version which supports the latest Magento version. After the release, we will look at the bug fixes on the backlog. 

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment] 2022-06-27 11:20
Hi @ZIPITRO ,

In our newest version, this should be fixed.  You can install the new version on a staging environment to test. 

Have a great day,
Jeffrey

**Comment by ZIPITRO** [comment] 2022-06-28 08:36
Hi Jeffrey,

Thanks for your update! 
But it looks like it introduced another issue, now we experience the billing house number missing, I just  created an issue(challenge) for this.
We had to update to 1.12.2 because of the security announcement made by PostNL.

Please have a look and let us know, thanks for your time!

**Comment by tig-jeffreybranderhorst** [comment] 2022-07-15 12:41
Hi @ZIPITRO ,

Thank you, we already had contact in the issue, but I see this issue was this open. So once again, thank you for submitting issues and thinking along! 

Have a great day,
Jeffrey

**Closed by tig-jeffreybranderhorst** 2022-07-15 12:41 UTC
Labels: verified bug
