### ISSUE TITLE
 PHP Fatal error:  Uncaught Error: Call to a member function getOriginalShippingAddress() on null

### ISSUE THREAD

**Issue by JerVoo** [tig-nl/postnl-magento2#96] opened 2019-02-11 14:27 UTC
### Make sure you are using the *latest* version: https://tig.nl/postnl-magento-extensies/
Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running the latest version of the TIG PostNL Magento extension.

PostNL version 1.7.3, Magento 2.3.0

---

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [X] Bug report (encountered problems with the TIG PostNL Magento extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

### If the purpose of your issue is a *bug report*
**Please describe the precise steps to reproduce your issue:**
- Create an order
- Select the order from the
- Select the "Create Shipments, Print Packslips & Confirm" option

**Expected result**
Shipments will be created and packingslips will be displayed

**Actual result (Please provide screenshots if applicable)**
```PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getOriginalShippingAddress() on null in /data/web/magento2/vendor/tig/postnl-magento2/Helper/Tracking/Mail.php:155
Stack trace:
#0 /data/web/magento2/vendor/tig/postnl-magento2/Helper/Tracking/Mail.php(134): TIG\PostNL\Helper\Tracking\Mail->getTemplateVars(Object(Magento\Sales\Model\Order\Interceptor), 'https://postnl....')
#1 /data/web/magento2/vendor/tig/postnl-magento2/Helper/Tracking/Track.php(212): TIG\PostNL\Helper\Tracking\Mail->set(Object(Magento\Sales\Model\Order\Shipment\Interceptor), 'https://postnl....')
#2 /data/web/magento2/vendor/tig/postnl-magento2/Helper/Tracking/Track.php(148): TIG\PostNL\Helper\Tracking\Track->sendTrackAndTraceEmail(Object(Magento\Sales\Model\Order\Shipment\Interceptor), Object(TIG\PostNL\Model\Shipment))
#3 /data/web/magento2/vendor/tig/postnl-magento2/Observer/TIGPostNLSetConfirmedAtBefore/SendTrackAndTraceEmail.php(61): TIG\PostNL\Helper\Tracking\Track->send(Object(Magento\Sales\Model\Order\Ship
```

**Workaround (If available, otherwise just write "None")**
None

**Comment by tig-jeffreybranderhorst** [comment] 2019-02-13 08:56
Hi @JerVoo,

I Just tested this on a clean Magento install with PostNL and I cannot reproduce this issue. Are you using other extensions that are using the code of the orders or mail functions? Because it could be a conflict with another extension. Is it possible you test this on a clean Magento?  If this problem still persists could you then send a mail towards us via servicedesk@tig.nl.

Best regards,
Jeffrey Branderhorst

**Comment by tig-jaspersmits** [comment] 2019-08-16 07:49
I will close this issue due to not receiving a response for 6 months.

**Closed by tig-jaspersmits** 2019-08-16 07:49 UTC
Labels: can't reproduce
