### ISSUE TITLE
[BUG] Double tax amount is removed 

### ISSUE THREAD

**Issue by twosg** [tig-nl/postnl-magento2#304] opened 2022-05-06 12:21 UTC
**To Reproduce**
1. Configure extension with matrix rates
2. Go to checkout and ship to address with a valid non-domestic VAT number (or use any user without VAT)

**Expected result**
The shipping price should be without the regular tax amount

**Actual result**
The shipping price is without the doubled regular tax amount

**Workaround**
Comment this line https://github.com/tig-nl/postnl-magento2/blob/master/Service/Carrier/Price/Matrixrate.php#L110

** Please complete the following information**
- Magento version: 2.4.3
- PHP version: 7.4
- TIG PostNL version: 1.12.1

#### Example
- shipping price incl. tax 10,-€
- should be 8,26€ without 21% tax
- but is 6,52€

**Comment by tig-jeffreybranderhorst** [comment] 2022-05-06 13:32
Hey @twosg,

Thank you for submitting this issue, with the steps to reproduce it, we are going to test this! 
And if we can reproduce it, we are going to place it on our backlog to fix the issue.

Have a nice day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment] 2022-05-09 14:30
Hi @twosg ,

We cannot reproduce this issue, Is it possible you share your tax settings with us, so we can test with the same settings as you? 

Have a great day,
Jeffrey

**Comment by tig-vincentthart** [comment] 2022-06-15 12:18
Hi @twosg,

Because we did not receive an update on this ticket we will close it.

If you have any questions about the plugin or ran into issues, you can contact PostNL directly at [digitaleklantsupport@postnl.nl](mailto:digitaleklantsupport@postnl.nl)

Have a great day!
Vincent

**Closed by tig-vincentthart** 2022-06-15 12:18 UTC
Labels: to be tested
