### ISSUE TITLE
Magento2 for PostNL Module print label or confirm shipment report

### ISSUE THREAD

**Issue by viktor-shatylo** [tig-nl/postnl-magento2#46] opened 2018-03-15 07:26 UTC
Installed module on Magento v.2.2.2
Magento Mode: Production
PostNL module mode: Test
PostNL module v.1.3.2

Got an error report when try to print or confirm shipment via PostNL

Steps to reproduce:
1. Place an order and choose 'PostNL' as shipping method

2. Ship an order via magento back-office

3. Print label or Confirm shipment

Report looks like next:
Can't create directory /generated\/code\/TIG\/PostNL\/Service\/Shipment\/Label\/Type\/. in [TIG\\PostNL\\Service\\Shipment\\Label\\Type\\EPSFactory]

All generating classes should be created during di compilation.
Please, include Factory classes and keep them in module :

TIG\\PostNL\\Service\\Shipment\\Label\\Type\\EPSFactory

TIG\\PostNL\\Service\\Shipment\\Label\\Type\\DomesticFactory

**Comment by tig-jaspersmits** [comment] 2018-03-28 08:50
Good morning Viktor,

Thank you for your message. Just tried to reproduce this on the same Magento version in combination with that version of the extension but was unable to do so. So if i understand it correctly you don't receive a label when you do this? Or do you get a label but the error is still shown?

Please kindly fill in in our template for reporting these kind of issues. 

Kind regards,

Jasper
TIG

-----

### Submitting issues trough Github
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: https://tig.nl/postnl-magento-extensies/
Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running the latest version of the TIG PostNL Magento extension.

---

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with the TIG PostNL Magento extension)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood]. Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

### TIG supportdesk

On Github we will respond in English even when the question was asked in Dutch.

**Comment by agorbulin** [comment] 2019-05-22 10:37
Hello.
I confirm the problem.

**Precognition:**
- Magento Cloud (EE) 2.2.7
- Tig PostNL 1.7.4
- read only FS (folder 'generated' is not writable on cloud environment)

**Steps to reproduce:**
- press any button ('PostNL - Confirm And Print Shipment Label', 'PostNL - Generate Label', 'PostNL - Print Packingslip') on shipment in Magento BO 

**Expected result:**
- no errors

**Actual result:**
- Magento creates report file:
{"0":"Can't create directory \/generated\/code\/TIG\/PostNL\/Service\/Shipment\/Labelling\/Handler\/.\n
Class TIG\\PostNL\\Service\\Shipment\\Labelling\\Handler\\GlobalpackFactory generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. 
If --- after running the 'bin\/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only.","1":"

#0 \/vendor\/magento\/framework\/Code\/Generator\/Autoloader.php(35): Magento\\Framework\\Code\\Generator->generateClass('TIG\\\\PostNL\\\\Serv...')\n
#1 [internal function]: Magento\\Framework\\Code\\Generator\\Autoloader->load('TIG\\\\PostNL\\\\Serv...')\n
#2 [internal function]: spl_autoload_call('TIG\\\\PostNL\\\\Serv...')\n
#3 \/vendor\/magento\/framework\/Code\/Reader\/ClassReader.php(19): ReflectionClass->__construct('TIG\\\\PostNL\\\\Serv...')\n
#4 \/vendor\/magento\/framework\/ObjectManager\/Definition\/Runtime.php(44): Magento\\Framework\\Code\\Reader\\ClassReader->getConstructor('TIG\\\\PostNL\\\\Serv...')\n
#5 \/vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php(100): Magento\\Framework\\ObjectManager\\Definition\\Runtime->getParameters('TIG\\\\PostNL\\\\Serv...')\n
#6 \/vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php(150): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('TIG\\\\PostNL\\\\Serv...')\n
#7 \/vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php(125): Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('TIG\\\\PostNL\\\\Serv...')\n
#8 \/vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php(86): Magento\\Framework\\ObjectManager\\Factory\\Compiled->parseArray(Array)\n
#9 \/vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php(150): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('TIG\\\\PostNL\\\\Serv...')\n
#10 \/vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php(79): Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('TIG\\\\PostNL\\\\Serv...')\n
#11 \/vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php(150): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('TIG\\\\PostNL\\\\Serv...')\n
#12 \/vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php(79): Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('TIG\\\\PostNL\\\\Serv...')\n
#13 \/vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php(150): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('TIG\\\\PostNL\\\\Serv...')\n
#14 \/vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php(79): Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('TIG\\\\PostNL\\\\Serv...')\n
#15 \/vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php(150): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('TIG\\\\PostNL\\\\Serv...')\n
#16 \/vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php(79): Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('TIG\\\\PostNL\\\\Serv...')\n
#17 \/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(56): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('TIG\\\\PostNL\\\\Cont...', Array)\n
#18 \/vendor\/magento\/framework\/App\/ActionFactory.php(40): Magento\\Framework\\ObjectManager\\ObjectManager->create('TIG\\\\PostNL\\\\Cont...')\n
#19 \/vendor\/magento\/framework\/App\/Router\/Base.php(297): Magento\\Framework\\App\\ActionFactory->create('TIG\\\\PostNL\\\\Cont...')\n
#20 \/vendor\/magento\/framework\/App\/Router\/Base.php(158): Magento\\Framework\\App\\Router\\Base->matchAction(Object(Magento\\Framework\\App\\Request\\Http), Array)\n
#21 \/vendor\/magento\/framework\/App\/FrontController.php(50): Magento\\Framework\\App\\Router\\Base->match(Object(Magento\\Framework\\App\\Request\\Http))\n
#22 \/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n
#23 \/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', Array)\n
#24 \/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n
#25 \/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, Array)\n
#26 \/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n
#27 \/vendor\/magento\/framework\/App\/Bootstrap.php(257): Magento\\Framework\\App\\Http->launch()\n
#28 \/pub\/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))\n
#29 {main}","url":"\/postnl\/shipment\/confirmAndPrintShippingLabel\/shipment_id\/701\/key\/##key##\/","script_name":"\/index.php"}

**Comment by tig-dennisvanderhammen** [comment] 2019-05-23 08:53
Hi @agorbulin,

I'm trying to reproduce this problem on a local environment, but it seems that as soon as I change the permissions to read-only, Magento gives an error on a lot of Magento classes (even after running setup/di/compile).

Could you tell me what the permissions are on a Magento Cloud environment? Do you have any suggestions about how  I can get these Magento classes generated? (generated/code/Magento/Framework/App/ResourceConnection/)
Whenever I try to find a solution on the internet, everybody simply recommends increasing the permissions on the generated folder, but obviously that is not the correct solution for Magento Cloud users.

**Comment by agorbulin** [comment] 2019-05-23 09:00
Hello.


You can reproduce it locally in production mode (not in developer):

- set production mode:

php bin/magento deploy:mode:set production --skip-compilation

- compile DI

php bin/magento setup:di:compile


- check generated/code/TIG/PostNL/Service/Shipment/Labelling/Handler, it should be exist


In developer mode it generated on demand, but in production mode must be generated during compile DI

Thank you.

________________________________

**Comment by tig-dennisvanderhammen** [comment] 2019-05-23 09:41
Hi @agorbulin, thank you for the quick response.

It seems that the GlobalpackFactory does get generated with setup:di:compile, at least on the develop branch with Magento 2.3.1.

I'll set up an M2.2.7 (CE) environment together with PostNL 1.7.4 to see if I'm able to reproduce it there.

**Comment by tig-dennisvanderhammen** [comment] 2019-06-11 12:33
Hi @viktor-shatylo and @agorbulin,

After testing this on older Magento versions (2.2.*) it seems that there is a difference between how Magento generates things in 2.2 and 2.3.

I've created a fix for this issue and this will be included in the upcoming release.

Thank you again for helping us reproduce the problem.

**Closed by tig-dennisvanderhammen** 2019-06-11 12:33 UTC
Labels: fixed
