### ISSUE TITLE
[BUG] v1.12.1 not compatible with Magento 2.4.4

### ISSUE THREAD

**Issue by Tjitse-E** [tig-nl/postnl-magento2#305] opened 2022-05-10 14:16 UTC
Related issue: https://github.com/tig-nl/postnl-magento2/issues/299#issue-1203224188

In [this comment](https://github.com/tig-nl/postnl-magento2/issues/299#issuecomment-1098767243) I found out that the latest version of the PostNL module is actually not compatible with Magento 2.4.4.

This should be declared in the composer.json [here](https://github.com/tig-nl/postnl-magento2/blob/master/composer.json#L7) so that it is not possible to install the PostNL module on a Magento 2.4.4 instance.

**Please complete the following information**
- Magento 2.4.4
- PHP version 7.4
- TIG PostNL 1.12.1

**Comment by richardreen** [comment] 2022-05-13 06:45
The upgrade to 2.4.4 is now stuck for several weeks only on this extension.!!!
When will this be solved no? Timeframe?

**Comment by tig-jeffreybranderhorst** [comment] 2022-05-13 07:08
Hi @richardreen ,

In the testing phase, we came across some issues that need to be fixed before releasing. Because of this, I cannot give a timeframe for the extension. We understand people are waiting on this release, that is why we are trying to push it live as soon as possible.

Have a great day,
Jeffrey

**Comment by kaybeudeker** [comment] 2022-05-17 07:49
Any news regarding this upcoming release? Magento 2.4.4 (GA) is out in the wild more than a month already so an(y) indication would be great. 

Thanks! 👍🏼

**Comment by tig-jeffreybranderhorst** [comment] 2022-05-17 10:58
Hi @kaybeudeker @richardreen @Tjitse-E,

First of all, I want to say that we fully understand your situation, and we are aware that it is holding you back from upgrading to Magento 2.4.4. TIG has its own merchants as well that are waiting for the compatibility release. Thank you for your feedback and patience.

The compatibility release has our full attention and top priority. We are working hard every day on making a release possible as soon as possible. 

I’d like to share with you some details of where we are: Besides the earlier mentioned log issue, we are also facing a front-end issue where the addresses are not shown properly in all test scenarios. Furthermore, there is a problem with a specific setting of the extension that labels won't print or will print twice. Although not every merchant uses A6 labels for printing, this needs to be fixed for the release, as it's core functionality required for order processing. The cause is known, the resolution is more complex as it is a standard library that is used all over for a long time that suddenly needs to be analyzed for refactoring or replacement. This is what we are working on and are far in the process already. A new internal release candidate is about to be released in the upcoming days.

As the PostNL extension is used by many merchants in both the Netherlands and Belgium, the impact is very high when a release contains bugs or even worse, does not work in all different merchant situations. Therefore, there is a line of fully automated tests, functionality and regression tests that needs to be passed on two test teams (TIG and PostNL) before a release is approved. This takes time. We are lined up in the procedures and do our very best to release as soon as possible, but therefore I can’t give you an exact date yet. We also don’t want to give you unnecessary “we are working on it” replies when there is nothing for you to see, download or test.

As soon as all tests are passed and the procedure is completed, we will update the release documentation and provide you with a date. 

Also, feel free to contact me directly at jeffrey@tig.nl if you would like to participate in our internal Hackathons to challenge extension code and processes and make a difference. We order from the best Pizza place in Amsterdam and have a great time guaranteed.

Have a great day,
Jeffrey.

**Comment by tig-jeffreybranderhorst** [comment] 2022-06-01 07:36
Hello, 

I thought I'd give you a brief update regarding the Magento Compatibility release. First the latest news, there will be no release this week, followed by the good news the release date is coming close. We are working on the last 6 open Q/A items. We are finalizing the known bug at Magento https://github.com/magento/zf1/pull/47 in this release. As many of you know, the PostNL functionality works around building PDF files for printing labels. While Magento still uses the PDF functionality of Zend Framework 1. We have decided to move the last of our Zend Framework 1 PDF functionality (barcode generation for packing slips and label concatenation) over to FPDI to be PHP 8.1 compatible.

The plan is still to release it as soon as possible, if the stars are aligned it could be next week.  

Cheers,
Jeffrey.

**Comment by Esteraa** [comment] 2022-06-10 08:27
@tig-jeffreybranderhorst Do you have a new update for us? I was hoping on a release this week. I would like to inform our customers who are also waiting on news about the update.

**Comment by tig-jeffreybranderhorst** [comment] 2022-06-10 10:55
Hi all,

We are finalizing the release. Most issues we found have been solved and right now we are having an issue with virtual products. After this issue has been solved, we will make a release.

How it is looking right now, this will be next week.

Have a great day,
Jeffrey

**Comment by DreamsitesWebdesign** [comment] 2022-06-10 13:17
Until the release, what is wise to do? Disable the extension or complete uninstall it? If I do the latter I'm afraid to loose all data....
Please advise

**Comment by tig-jeffreybranderhorst** [comment] 2022-06-10 14:18
Hi @DreamsitesWebdesign ,

You could disable the extension until we release the new version if you are having problems with it. 

Have a great day,
Jeffrey

**Closed** 2022-06-15 12:05 UTC

**Comment by DreamsitesWebdesign** [comment] 2022-06-16 07:16
Thank you for the update.
Installed v1.12.2 and everything seems to be working fine.


Met vriendelijke groet,
Dreamsites Webdesign
Michael Blankenberg

***@***.***
webdesign | webhosting | content management


  Bekijk hier onze portfolio: www.dreamsites.nl/portfolio<https://www.dreamsites.nl/portfolio>

Elzenweg 33
5144 MB Waalwijk
+31(0)416 567 333
***@***.******@***.***>
www.dreamsites.nl<http://www.dreamsites.nl/>



Van: tig-vincentthart ***@***.***>
Verzonden: woensdag 15 juni 2022 14:06
Aan: tig-nl/postnl-magento2 ***@***.***>
CC: Michael Blankenberg ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tig-nl/postnl-magento2] [BUG] v1.12.1 not compatible with Magento 2.4.4 (Issue #305)


Good afternoon,

We have just released v1.1.2.2 with support for Magento 2.4.4. Thank you all for your patience an thinking along.

Have a nice day!
Vincent

**Comment by DreamsitesWebdesign** [comment] 2022-10-11 07:32
Unfortunately the shipping address is still missing when I do so….


***@***.***



***@***.***



Met vriendelijke groet,
Dreamsites Webdesign
Michael Blankenberg


[logo_dreamsites2013]

Bekijk hier onze portfolio: www.dreamsites.nl/portfolio<https://www.dreamsites.nl/portfolio>

Postbus 641, 5140 AP Waalwijk
Elzenweg 33, 5144 MB Waalwijk
0416 - 567 333
0416 - 652 179
***@***.******@***.***>
www.dreamsites.nl<http://www.dreamsites.nl/>
FB.          facebook.com/dreamsites.web<http://www.facebook.com/dreamsites.web>



Van: Jeffrey Branderhorst ***@***.***>
Verzonden: vrijdag 10 juni 2022 16:18
Aan: tig-nl/postnl-magento2 ***@***.***>
CC: Michael Blankenberg ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [tig-nl/postnl-magento2] [BUG] v1.12.1 not compatible with Magento 2.4.4 (Issue #305)


Hi @DreamsitesWebdesign<https://github.com/DreamsitesWebdesign> ,

You could disable the extension until we release the new version if you are having problems with it.

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment] 2022-10-11 08:20
Hi @DreamsitesWebdesign ,

We cannot reproduce this anymore on our testing website. I would like to ask you send a mail to digitaleklantsupport@postnl.nl for further support, so we can investigate your website/situation. 

Have a great day,
Jeffrey
