### ISSUE TITLE
[BUG] Incorrect table rate due to incorrect sorting

### ISSUE THREAD

**Issue by mlaurense** [tig-nl/postnl-magento2#293] opened 2022-03-08 10:20 UTC
When filtering the table rates, the matrixrateCollection is [sorted using only the subtotal](https://github.com/tig-nl/postnl-magento2/blob/master/Service/Carrier/Price/Matrixrate.php#L97) (descending). But this breaks the correct rate calculation when using weight. Given a cart of ~ 35kg of weight, after filtering the rates in `vendor/tig/postnl-magento2/Service/Carrier/Price/Matrixrate.php`, these two rates are remaining:

![Schermafbeelding 2022-03-08 om 10 42 14](https://user-images.githubusercontent.com/16759472/157214828-45d98fbd-357e-4050-976b-d8db4f949e55.png)

This will incorrectly return a shipping of € 5, while it should return € 10.

Possibly related to https://github.com/tig-nl/postnl-magento2/issues/224 as well

**To Reproduce**
1. Create two rates using the example in the screenshot
2. Add enough items to the cart so the weight of the second rate should be used
3. See it return the lower of the two rates

**Expected result**
Shipping should be € 10

**Actual result**
Shipping is € 5

**Workaround**
Modify https://github.com/tig-nl/postnl-magento2/blob/master/Service/Carrier/Price/Matrixrate.php#L97 to also sort by weight:
```        $matrixrateCollection     = $this->matrixrateCollection->addOrder('subtotal', 'DESC')->addOrder('weight', 'DESC');```

After filtering, the rates are returned as follows:

![Schermafbeelding 2022-03-08 om 11 18 19](https://user-images.githubusercontent.com/16759472/157216760-9cca0b9d-8faa-40e7-92fd-1ed331a02a07.png)

**Please complete the following information**
- Magento version: 2.4.2-p2
- PHP version: 7.4
- TIG PostNL version: 1.10.1

**Comment by tig-jeffreybranderhorst** [comment] 2022-03-09 08:13
Hi @mlaurense, 

Thank you for submitting this issue with this much information. We are going to test it, I do have some questions. You are using the matrix rates not the table right, am I correct?   And would it be possible to share your matrix rate, so we are testing with the same rates? 

Have a great day.
Jeffrey

**Comment by mlaurense** [comment] 2022-03-09 08:26
Hi @tig-jeffreybranderhorst,

Yes, it is matrix rates (my bad). I attached the used rates:

[matrixrate-test.csv](https://github.com/tig-nl/postnl-magento2/files/8212906/matrixrate-test.csv)

**Comment by tig-jeffreybranderhorst** [comment] 2022-03-09 11:37
Hi @mlaurense,

Thank you for the matrix rates we are going to test this! 

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment] 2022-03-14 08:56
Hi @mlaurense,

We have tested your matrix, and we can reproduce the last price is not reached because the 50 and above comes first, and then he will stop there instead of going to the 75. We will test your PR thank you for submitting this! 

Have a great day,
Jeffrey

**Comment by tig-vincentthart** [comment] 2022-06-15 12:50
Hi @mlaurense ,

We have just released v1.12.2 and included a fix for this. Thank you for the detailed description.

Have a nice day!
Vincent

**Closed by tig-vincentthart** 2022-06-15 12:50 UTC
Labels: verified bug
