### ISSUE TITLE
[BUG] Letterbox with configurable product not wokring

### ISSUE THREAD

**Issue by ruthgeridema** [tig-nl/postnl-magento2#267] opened 2021-09-16 16:02 UTC
**To Reproduce**
1. Set a simple product (which is part of a config product) to LETTERBOX shipping

**Expected result**
You would expect that the proposed shipment is LETTERBOX

**Actual result**
Normal shipment with time-picker is shown

- TIG PostNL version: latest

**Comment by tig-jeffreybranderhorst** [comment] 2021-09-17 07:23
Hey @ruthgeridema ,

In the PostNL settings your letterbox should also be set to automatic otherwise it won't automatically be a letterbox shipment and the product settings it should say how many of that product can be in a letterbox. Only making a product be letterbox is not enough. For more support you can contact PostNL at digitaleklantsupport@postnl.nl.

Have a great day,
Jeffrey

**Comment by ruthgeridema** [comment] 2021-09-17 08:01
Hi @tig-jeffreybranderhorst ,

We also did that. It works when a simple product is 'seperate' and not part of a config product.

**Comment by tig-jeffreybranderhorst** [comment] 2021-09-17 08:16
Hi @ruthgeridema ,

Could you contact PostNL at digitaleklantsupport@postnl.nl for more support on this issue?

Have a great day,
Jeffrey

**Comment by memen45** [comment] 2021-09-29 12:27
Same problem here. It was working before, so I suspect it is caused by the last update. Were you able to resolve the issue?

**Comment by tig-jeffreybranderhorst** [comment] 2021-09-29 13:43
Hi @memen45 ,

If you are also having this issue you should contact digitaleklantsupport@postnl.nl for support.

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment] 2021-11-19 10:05
Hi @memen45 ,

This should be fixed in 1.10, our newest version of postnl.

Have a great day,
Jeffrey

**Closed by tig-jeffreybranderhorst** 2021-11-19 10:05 UTC
