### ISSUE TITLE
Composer conflict installing new version on magento 2.3.3

### ISSUE THREAD

**Issue by TomMeijnaerts** [tig-nl/postnl-magento2#149] opened 2020-01-16 14:51 UTC
Magento 2.3.3

when installing magento the package `magento/product-community-editions `installs the temado/module-shipping v1.6.1 module.

The temado/module-shipping v1.6.1 has following line in its composer.json :
`"zendframework/zend-barcode": "^2.7.0",`

+- 28 days ago there is a zendframework/zend-barcode v2.8. the line in temado/module-shipping installs the 2.8 version. ( notice the ^ before version number )

Because the postnl-magento2 module has 
`"zendframework/zend-barcode" : "~2.5.2|~2.7.0"` you will get composer errors when adding the post-nl composer package. (notice the ~ instead of ^)

Adding `        "zendframework/zend-barcode": "^2.7.1"` to your composer.json fixes the problem ... but its not really plug and play anymore.

**Comment by tig-dennisvanderhammen** [comment] 2020-01-16 14:54
Hi @TomMeijnaerts ,

Thank you for submitting this.
I would like to ask you to use the issue template in the future.

This seems to be a duplicate of issue #145, which is already on our backlog to solve. To prevent communication on on multiple pages about one issue, I will be closing this one.

**Closed by tig-dennisvanderhammen** 2020-01-16 14:54 UTC
