### ISSUE TITLE
[BUG] Delivery date wrong, shows date from the past

### ISSUE THREAD

**Issue by nebojsa-factorblue** [tig-nl/postnl-magento2#314] opened 2022-06-06 10:10 UTC
Hello,

We are facing a problem that was claimed as fixed earlier. 

A customer on our Client's shop purchased on the 27th of May and selected delivery date that shows in Magento as the 4th of October 2018. 

**To Reproduce**
Make an order with a selected delivery date. Does not happen every time. 

**Expected result**
Show the selected date.

**Actual result**
Date from the past.

**Workaround**
None.

**Screenshots**
Backend: https://i.imgur.com/EdxZIkf.png
Database: https://i.imgur.com/VE8FHbN.png

- Magento version: 2.4.3
- PHP version: 7.4.29
- TIG PostNL version: 1.12.1. The latest version was installed on the webshop on the 5th of May 2022., 3 weeks before placing that order. 

Thanks!

**Comment by tig-jeffreybranderhorst** [comment] 2022-06-07 09:26
Hi @nebojsa-factorblue,

Thank you for submitting this! We are investigating similar issues with exports. We will also investigate this issue! 
Thanks again for bringing this to our attention.

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment] 2022-06-20 09:16
Hi @nebojsa-factorblue ,

It is on our backlog, and we are investigating this, but we don't seem to be able to reproduce it. And without reproduction, we cannot make a fix for it. So if you know how to reproduce this, please let us know, so we can make a fix for it. 

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment] 2022-07-15 13:20
Hi @nebojsa-factorblue ,

After a lot of testing and talking to PostNL we were not able to reproduce it and PostNL decided to not investigate this further. And first fix other bugs and make new features.  Because of this, it is decided we will close this github issue.

Have a great day,
Jeffrey

**Closed by tig-jeffreybranderhorst** 2022-07-15 13:20 UTC
Labels: on backlog

**Comment by nebojsa-factorblue** [comment] 2022-07-18 06:52
No problem. We managed to solve it on our side. It is not a problem to share more info with you, only if you are interested. 

Regards,
Nebojsa S
