### ISSUE TITLE
Uncaught Error: Call to a member function getAdditionalInformation() on null in vendor/magento/module-sales/Model/OrderRepository.php:172

### ISSUE THREAD

**Issue by s1104373** [tig-nl/postnl-magento2#99] opened 2019-03-28 17:56 UTC
### Make sure you are using the *latest* version: https://tig.nl/postnl-magento-extensies/
Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG PostNL Magento extension.

I'm using magento 2.3.1 and TIG PostNL 1.7

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [x] Bug report (encountered problems with the TIG PostNL Magento extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

### If your issue contains security sensitive information
** If your issue may contain sensitive information, please send us an e-mail at security@tig.nl.**
- [x] This issue does not contain any security sensitive information

### If the purpose of your issue is a *bug report*
**Please describe the precise steps to reproduce your issue:**

- Steps to reproduce
1. Add product to cart
2. Go through shipping step for checkout
3. select payment method
4. click button place order
 
- Expected result
The order is placed

- Actual result (Please provide screenshots if applicable)
An error occurs. No exception message is show on page.
error (obtained via console): 
`code: 500
message: "Fatal Error: 'Uncaught Error: Call to a member function getAdditionalInformation() on null in /home/bart/magento_projects/ucw2/vendor/magento/module-sales/Model/OrderRepository.php:172↵Stack trace:↵#0 /home/bart/magento_projects/ucw2/vendor/magento/module-sales/Model/OrderRepository.php(134): Magento\Sales\Model\OrderRepository->setPaymentAdditionalInfo(Object(Magento\Sales\Model\Order\Interceptor))↵#1 /home/bart/magento_projects/ucw2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\OrderRepository->get('21')↵#2 /home/bart/magento_projects/ucw2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\OrderRepository\Interceptor->___callParent('get', Array)↵#3 /home/bart/magento_projects/ucw2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\OrderRepository\Interceptor->Magento\Framework\Interception\{closure}('21')↵#4 /home/bart/magento_projects/ucw2/generated/code/Magento/Sales/Model/OrderRepository/Interceptor.php(26): Magento\Sales\Model\' in '/home/bart/magento_projects/ucw2/vendor/magento/module-sales/Model/OrderRepository.php' on line 172"
trace: "Trace is not available."`

- Workaround (If available, otherwise just write "None")
None

**Comment by Gerjan98** [comment] 2019-03-28 18:21
git gud

**Comment by s1104373** [comment] 2019-03-28 19:23
Tested it on magento 2.3.0. Same issue is present

**Comment by simonjanguapa** [comment] 2019-04-02 13:52
We're having the same issue; although I could place an order while using Magento 2.3.0.
Same exception as stated above is thrown while using Magento 2.3.1.

**Comment by WJdeBaas** [comment] 2019-04-02 14:16
Same issue on Magento 2.3.1 and tig/postnl-magento2 version 1.7.3

**Comment by tig-dennisvanderhammen** [comment] 2019-04-02 14:37
Hi @s1104373,

Thank you for submitting your issue.

I'm unable to reproduce your error on Magento 2.3.0. It seems that the getAdditionalInformation() method is not present in this version yet.

We did also encounter this bug in Magento 2.3.1. It seems that Magento changed how their get() function in the OrderRepository works. We try to get the Magento Order at a moment where the order does have an entity_id (therefore no NoSuchEntityException is thrown), but the Order object doesn't have a Payment yet.

My colleague just pushed a branch with a fix on our private repository, which is currently awaiting the Travis tests.

**Comment by WJdeBaas** [comment] 2019-04-03 08:47
Quick fix:
In class TIG\PostNL\Observer\TIGPostNLOrderSaveBefore\SetDefaultData , private function checkByAddressData , comment the lines 212, 213, 214, like below

        //if (!$address && $order->getOrderId()) {
        //    $address = $this->magentoOrder->getShippingAddress($order->getOrderId());
        //}

That will prevent the ordermodel from initiating

**Comment by tig-dennisvanderhammen** [comment] 2019-04-03 08:56
@WJdeBaas , this function is also used when creating a shipment. This would mean the wrong data might be send towards PostNL (for example, when the shipping address has been changed in the backend).

A better quick fix would be placing a try/catch block around it:
try {
    if (!$address && $order->getOrderId()) {
        $address = $this->magentoOrder->getShippingAddress($order->getOrderId());
    }
} catch (\Error $e) {
}

**Comment by WJdeBaas** [comment] 2019-04-03 09:06
Catching an exception and do nothing with it is a bad example of quality coding standards.
A better option would be to get the shipping address from the order when the shipment is to be created.

**Comment by tig-dennisvanderhammen** [comment] 2019-04-03 09:47
This would be a workaround. In our private branch we have a fix that is alike, but it doesn't have an empty catch.

**Comment by simonjanguapa** [comment] 2019-04-03 11:48
Yep, the workaround works fine. Any idea when this fix is going to be released publicly?

**Comment by tig-dennisvanderhammen** [comment] 2019-04-03 12:36
I'm unable to give an exact date right now. After our fixes are done we still have to test the extension to see if everything works properly.
We'll get an official version out as soon as we can.

**Comment by tig-dennisvanderhammen** [comment] 2019-04-08 12:58
Hi everybody,

Thanks again for your suggestions. We just released version v1.7.4 which has a fix for this issue.

**Closed by tig-dennisvanderhammen** 2019-04-08 12:58 UTC
