### ISSUE TITLE
[BUG] Track & Trace mail doesn't show shipping address for PostNL-locations

### ISSUE THREAD

**Issue by kaybeudeker** [tig-nl/postnl-magento2#308] opened 2022-05-17 13:55 UTC
When an order is placed with a PostNL-location as shipping address, the track & trace mail (the one from the TIG-extension, not Magento's default shipment confirmation) doesn't show the address of the selected PostNL-location. Instead, the billing address is shown. When the shipping address differs from the billing address, but it's not a PostNL-location, this shipping address is shown correctly in the track & trace mail. 

I'm aware of issue #303 but that doesn't seems to be related to this issue.

**To Reproduce**
1. Frontend: Place an order and select a PostNL-location as shipping address
2. Backend: Create shipment, print labels & confirm - Track & trace e-mail is send (well, depending on settings).
3. Check the Track & trace mail

**Expected result**
The selected PostNL-location as shown address

**Actual result**
The billing address is shown

**Workaround**
None

**Screenshots**
![Schermafbeelding 2022-05-17 om 15 53 02](https://user-images.githubusercontent.com/31165120/168827505-893050a2-f2be-4177-9264-ddf111834cda.png)

**Stack**
- Magento version: 2.4.3-p2
- PHP version: 7.4.28
- TIG PostNL version: 1.12.1

**Comment by tig-jeffreybranderhorst** [comment] 2022-05-17 14:43
Hi @kaybeudeker,

Thank you for submitting this issue, I'm going to test this! 
I will be back with an update.

Have a nice day,
Jeffrey

**Comment by kaybeudeker** [comment] 2022-05-17 15:10
Please look at `{{var url}}` as well! In this case it generates a URL that uses the postal code from the billing address!
It should use the same one as used on the shipping label, the PostNL-location's postal code.

**Comment by tig-jeffreybranderhorst** [comment] 2022-05-18 07:31
Hi @kaybeudeker,

I'm going to create a backlog issue that the pickup location should also been shown in the track and trace email. The address that is already shown should be the shipping address, same for the postal code in the URL, the URL needs the shipping postal code to collect the correct track and trace information. 

If your track and trace email and URL use the billing address, we would like to investigate this further because we cannot reproduce this part.  The part of the pickup location in the track and trace I will make a backlog issue for, thank you for submitting this. 

Have a great day,
Jeffrey

**Comment by kaybeudeker** [comment] 2022-05-18 13:53
Hey @tig-jeffreybranderhorst,

Great! Showing the billing address instead of the selected pickup address could confuse customers.

While adding the pickup address as an e-mail template var, would it also be possible to make the module's e-mail template vars available in Magento's default  order confirmation mail?
Reason for this is that when checking out as a guest with a delivery date in the future (up to 14 days allowed), a confirmation of that selection in the order confirmation mail would be a nice feature. Currently customers only could get this information from the PostNL track & trace mail, which normally would be send just the day before delivery.

Regarding my comment about `{{var url}}`, turns out that a PostNL track & trace link/url SHOULD contain the postal code of the billing address while a pickup point is the actual address for that shipment. Confirmed by my personal Bol.com track-and-trace mails for pickup-point-deliveries. My bad... 😄 

Thanks!

**Comment by tig-jeffreybranderhorst** [comment] 2022-05-19 07:14
Hi @kaybeudeker,

At this moment, I don't know if it is possible to make all PostNL vars available for all the email templates. I also place this on the backlog.  Thank you for thinking along.

Have a great day,
Jeffrey

**Comment by tig-vincentthart** [comment] 2023-03-24 14:28
Hi @kaybeudeker,

I have just tested this within the latest version of the plugin and there I got the pickup location correctly within the Track & Trace e-mail. Therefore I will close this issue.

If you still encounter any issues please contact PostNL at digitaleklantsupport@postnl.nl

Have a nice day!

Vincent

**Closed by tig-vincentthart** 2023-03-24 14:28 UTC
Labels: on backlog
