### ISSUE TITLE
[BUG] can't make new shipment with MSI setup

### ISSUE THREAD

**Issue by Fullstak-nl** [tig-nl/postnl-magento2#185] opened 2020-07-07 13:42 UTC
**To Reproduce**
1. Go to orders
2. Select order you want to send
3. click on actions and create postnl shipment

**Expected result**
Shipment created. returning to overview

**Actual result**
and error whichs says "Source item not found by source code: default and sku: R2 Smart Sensor Car Wireless Charger."

**Workaround**
None

**Screenshots**
![image](https://user-images.githubusercontent.com/55746426/86790094-4ed5fd00-c068-11ea-9e6d-75c88040d93c.png)

- Magento version: Magento 2.3.5
- PHP version: PHP 7.3.18
- TIG PostNL version: 1.9.3

**Comment by tig-jaspersmits** [comment] 2020-07-08 06:21
Hi @Fullstak-nl ,

Thanks for your message. I just tried reproducing this, but was unable to do so.
I assume you place the order through the frontend of the store first before following these steps, right?
Are you using any other extensions that might impact and be related to the problem?

Kind regards,
Jasper
TIG

**Comment by breakerh** [comment] 2020-07-08 09:49
@tig-jaspersmits Thanks for the fast respons!

Did you have stock set on other inventory's but default?
And we don't have any other plugin controlling our stock.

Thanks in advance!
Kind regards,
Bram

**Comment by tig-jaspersmits** [comment] 2020-07-09 06:35
Hi @breakerh ,

No problem! But.. no, I just followed the steps as mentioned in the opening comment.
If there are more steps, I need to to know what to do. If those steps can be provided I'll try to reproduce it again.

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment] 2020-07-13 11:58
This should be fixed in the new release.
I will close the ticket.

Kind regards,
Jasper
TIG

**Closed by tig-jaspersmits** 2020-07-13 11:58 UTC
Labels: question

**Comment by breakerh** [comment] 2020-07-27 00:53
It's not... But I am reworking it all since alot of plugins can't handle MSI... Now just one inventory and a special integer field for internal stock and another one for Marge(no VAT) stock..

**Comment by tig-jaspersmits** [comment] 2020-07-27 06:22
@breakerh I'll make sure we take another look at it.
Will inform you when I have more info.

Kind regards,
Jasper
TIG
