### ISSUE TITLE
Label not printed due to PDF compression technique not recognized

### ISSUE THREAD

**Issue by evs-xsarus** [tig-nl/postnl-magento2#192] opened 2020-07-31 09:09 UTC
**To Reproduce**
1. Go to 'Admin > Orders'
2. Select an order
3. Open pulldown 'Actions'
3. Click on 'Create shipments, print labels & confirm'

**Expected result**
An PDF label.

**Actual result**
An error code, the log says:
> {"0":"This PDF document probably uses a compression technique which is not supported by the free parser shipped with FPDI. (See https:\/\/www.setasign.com\/fpdi-pdf-parser for more details)","1":"#1 setasign\\Fpdi\\PdfParser\\CrossReference\\CrossReference->readXref() called at [vendor\/setasign\/fpdi\/src\/PdfParser\/CrossReference\/CrossReference.php:68]

**Workaround**
None

- Magento version: [Magento Community 2.3.4]
- PHP version: [7.3.0]
- TIG PostNL version: [1.9.4]

Complete log:

```json
{"0":"This PDF document probably uses a compression technique which is not supported by the free parser shipped with FPDI. (See https:\/\/www.setasign.com\/fpdi-pdf-parser for more details)","1":"#1 setasign\\Fpdi\\PdfParser\\CrossReference\\CrossReference->readXref() called at [vendor\/setasign\/fpdi\/src\/PdfParser\/CrossReference\/CrossReference.php:68]
#2 setasign\\Fpdi\\PdfParser\\CrossReference\\CrossReference->__construct() called at [vendor\/setasign\/fpdi\/src\/PdfParser\/PdfParser.php:158]
#3 setasign\\Fpdi\\PdfParser\\PdfParser->getCrossReference() called at [vendor\/setasign\/fpdi\/src\/PdfParser\/PdfParser.php:203]
#4 setasign\\Fpdi\\PdfParser\\PdfParser->getCatalog() called at [vendor\/setasign\/fpdi\/src\/PdfParser\/PdfParser.php:182]
#5 setasign\\Fpdi\\PdfParser\\PdfParser->getPdfVersion() called at [vendor\/setasign\/fpdi\/src\/PdfReader\/PdfReader.php:85]
#6 setasign\\Fpdi\\PdfReader\\PdfReader->getPdfVersion() called at [vendor\/setasign\/fpdi\/src\/FpdiTrait.php:215]
#7 setasign\\Fpdi\\Fpdi->setSourceFile() called at [vendor\/tig\/postnl-magento2\/Service\/Shipment\/Label\/Type\/Domestic.php:89]
#8 TIG\\PostNL\\Service\\Shipment\\Label\\Type\\Domestic->process() called at [vendor\/tig\/postnl-magento2\/Service\/Shipment\/Label\/Prepare.php:119]
#9 TIG\\PostNL\\Service\\Shipment\\Label\\Prepare->label() called at [vendor\/tig\/postnl-magento2\/Service\/Shipment\/Label\/Generate.php:86]
#10 TIG\\PostNL\\Service\\Shipment\\Label\\Generate->run() called at [vendor\/tig\/postnl-magento2\/Controller\/Adminhtml\/PdfDownload.php:224]
#11 TIG\\PostNL\\Controller\\Adminhtml\\PdfDownload->generateLabel() called at [vendor\/tig\/postnl-magento2\/Controller\/Adminhtml\/PdfDownload.php:141]
#12 TIG\\PostNL\\Controller\\Adminhtml\\PdfDownload->get() called at [vendor\/tig\/postnl-magento2\/Controller\/Adminhtml\/Order\/CreateShipmentsConfirmAndPrintShippingLabels.php:125]
#13 TIG\\PostNL\\Controller\\Adminhtml\\Order\\CreateShipmentsConfirmAndPrintShippingLabels->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:108]
#14 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\/magento\/module-backend\/App\/AbstractAction.php:231]
#15 Magento\\Backend\\App\\AbstractAction->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]
#16 TIG\\PostNL\\Controller\\Adminhtml\\Order\\CreateShipmentsConfirmAndPrintShippingLabels\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]
#17 TIG\\PostNL\\Controller\\Adminhtml\\Order\\CreateShipmentsConfirmAndPrintShippingLabels\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php:143]
#18 Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]
#19 TIG\\PostNL\\Controller\\Adminhtml\\Order\\CreateShipmentsConfirmAndPrintShippingLabels\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]
#20 TIG\\PostNL\\Controller\\Adminhtml\\Order\\CreateShipmentsConfirmAndPrintShippingLabels\\Interceptor->___callPlugins() called at [generated\/code\/TIG\/PostNL\/Controller\/Adminhtml\/Order\/CreateShipmentsConfirmAndPrintShippingLabels\/Interceptor.php:26]
#21 TIG\\PostNL\\Controller\\Adminhtml\\Order\\CreateShipmentsConfirmAndPrintShippingLabels\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:159]
#22 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:98]
#23 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]
#24 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]
#25 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]
#26 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]
#27 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:116]
#28 Magento\\Framework\\App\\Http->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:261]
#29 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:68]
","url":"\/admin_mcf\/postnl\/order\/CreateShipmentsConfirmAndPrintShippingLabels\/key\/14a56b9320feb7db6feaa17b7133b37289634320a2267b619904a00a3e3c2833\/","script_name":"\/index.php","report_id":"441347cdf19b44462fffa08e978ff0ae0bc85de1d019ce574e7a2e1bf52e6593"}
````

**Comment by tig-jaspersmits** [comment] 2020-07-31 09:20
Hi @evs-xsarus ,

Thanks for submitting this. I've justed tested it on a test environment, but I'm unable to reproduce this problem.
Seems to be related to FPDI to be honest. What version are you using for this extension?

Kind regards,
Jasper
TIG

**Comment by evs-xsarus** [comment] 2020-07-31 09:31
@tig-jaspersmits composer has set this versions:

```
"name": "setasign/fpdi",
"version": "v2.3.3",

"name": "setasign/fpdi-fpdf",
"version": "v2.2.0",
```

the latter, which is requested by tig/postnl-magento2, has this set in require

```
"setasign/fpdi": "^2.2"
```

Might be because I used this command?

```composer update tig/postnl-magento2 --with-dependencies```

**Comment by tig-jaspersmits** [comment] 2020-07-31 13:20
Hi @evs-xsarus ,

That version does seem higher then what we use. What version of PostNL are you running?
Running the composer command with --with-dependencies should not be necessary.

Kind regards,
Jasper
TIG

**Comment by evs-xsarus** [comment] 2020-07-31 13:22
@tig-jaspersmits I'm running:

```
            "name": "tig/postnl-magento2",
            "version": "1.9.4",
```

**Comment by tig-jaspersmits** [comment] 2020-07-31 13:35
Hi @evs-xsarus ,

Alright, that should be fine. You could try completely removing the SetaSign extensions and then run the PostNL installation command again to see if it installs the right version. If it doesn't work after that, I would like to take a look at it. But in this case, since I'm not able to reproduce the problem, it would be better if you contacted PostNL about this.

They can forward it to us so we have their approval of looking into this. You can contact them on digitaleklantsupport@postnl.nl or by phone on 088-2255651.

Kind regards,
Jasper
TIG

**Comment by evs-xsarus** [comment] 2020-07-31 14:00
@tig-jaspersmits I have performed this 2 commands:

```composer remove tig/postnl-magento2```
```composer require tig/postnl-magento2```

In between I verified that the module and those from setasign were indeed removed from vendor and composer.lock. They were. After the require, the 2.3 version is again added:

```
"name": "setasign/fpdi",
"version": "v2.3.3",
```
In my opinion, when you update your composer packages, you should also receive that version.

**Comment by tig-jaspersmits** [comment] 2020-07-31 14:09
@evs-xsarus,

I'll ask my colleague @tig-dennisvanderhammen to take a look at this.

Kind regards,
Jasper
TIG

**Comment by tig-dennisvanderhammen** [comment] 2020-10-12 12:50
Hi @evs-xsarus ,

We just released a new version. With setasign abandoning the package setasign/fpdf-fpdi, we've split the packages up. Could you try installing the latest version (with --update-with-dependencies) and see if you can still reproduce this issue?

**Comment by tig-jaspersmits** [comment] 2020-11-10 14:46
I will close this issue as it should be solved with the new release.
If there is anything else feel free to reopen the issue or create a new one.

Kind regards,
Jasper
TIG

**Closed by tig-jaspersmits** 2020-11-10 14:46 UTC
Labels: can't reproduce, question
