### ISSUE TITLE
Post NL block with delivery options disappear

### ISSUE THREAD

**Issue by viktor-shatylo** [tig-nl/postnl-magento2#60] opened 2018-07-16 08:50 UTC
Hello, 
We use PostNL 1.3.2  module on our magento EE 2.2.4 project.
We faced with problem that PostNL options disappear on checkout . 
Steps to reproduce:
1. go to checkout (as logged in) 
2. enter new address 
3. go to step 2 
4. back to step 1 

It happens because of you try to collect shipping address from general fields (see file AddressFinder.js) : street, postcode, city.

Please, take into account that on  second step of checkout there are  billing forms for each payment method that also contains fields 'street', postcode, city.

**Comment by tig-jeffreypeeters** [comment] 2018-07-16 12:51
Hey viktor-shatylo,

We've tried to reproduce your problem but we've had no success in doing so. Could you try updating your PostNL version to the latest version (1.4.3) and see if the problem persists? If the problem does persist could you tell us which checkout you are using in your magento project?

Kind regards,

Jeffrey
TIG

**Comment by tig-jeffreypeeters** [comment] 2018-08-13 10:44
Hey viktor-shatylo,

I'll be closing this issue as it has almost been a month since you've created this issue and we've not yet recieved an update from you regarding your problem. Feel free to contact us again if the problem persists.

Kind regards,

Jeffrey Peeters
TIG

**Closed by tig-jeffreypeeters** 2018-08-13 10:44 UTC
